### ISSUE TITLE
Changing Folder names in config for filters too

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#116]
**Originally by _opionline@yahoo.de_ on 2010-03-04 23:11:34 +0100**

___
Your recent changes in the YAM bugtracker forced me to rename a folder in my YAM installation. After i have renamed my folder the filter which move the mails to the folder was not working because of the changed name. I get a Error requester saying:

```
Die Nachricht 'PIK1QQAEeu4=.001,R' kann nicht in Postfach
'SourceForge' verschoben werden
```

Ein Postfach mit diesem Namen existiert nicht. Bitte die Filtereinstellungen überprüfen.

Now my request: If a user change the name of a mail folder YAM should be smart check if the name is used in any filter and if so then pop up a requester and ask the user if he want to change the name in the filter configuration too. That could avoid a lot of work to find all such names in the filterconfig.

BTW1: The mails was catched by another (later) filter and moved to the folder defined for this filter. I must look into the log to find out which in which folder YAM moved the mail. I not sure if YAM should do such things. IMHO it's not correct. A mail which fulfill all filter criterias but YAM can't do the action defined in this filter the mail should not checked by another filter and stay in the source folder. This would also avoid such unlogical log entrys like: 04.03.2010 01:02:01 [26] 2 Nachricht(en) in Postfach 'Eingang' filtriert: 4 Treffer

I know YAM has really 4 Treffer (2 which throw a error and 2 really moved mails) but such message is a little bit surprisingly.

**Comment by tboeckel** [comment]
**Originally on 2010-08-10 15:17:07 +0200**

___
Having two filters which should move one mail to two different folders is a buggy configuration from my point of view. As long as the first move operation succeeds the second filter will **never** be applied, because a successful move operation will abort the filter queue for that mail.

If such a situation should abort the filter queue is questionable. The mail was not moved and could be handled by other filters, which is no contradiction. One could imagine two filters of which the first performs a "play sound" action and the second one moves the mail to another folder. Of course, both actions could be combined into one single filter, but nobody can forbid such a setup.

**Comment by tboeckel** [comment]
**Originally on 2010-08-10 15:18:23 +0200**

___
The "do you want to apply the name change to the filters" feature will be implemented in the next nightly build.
