### ISSUE TITLE
Exporting/importing mbox file

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#118]
**Originally by _AmigaPhil@scarlet.be_ on 2010-03-04 23:18:52 +0100**

___
When YAM exports mail to a mbox file, the mail status is stored in:
- Status:
  R (read)
  O (old)
- X-status:
  R (read)
  A (answered/replied)
  D (deleted)
  F (flagged, marked by user)

(I'm not sure it's a good thing (compatibility ?) to place a "R" in the X-Status: header, the Status: header is already the place for this.)

When importing back that mbox file, YAM seems to ignore the Status: header.  Exporting an old unread mail - >
Status: O
X-Status: 
and importing it again, and the mail is then shown as NEW.

YAM should read and write the Read and Old status from the Status: header.

**Comment by tboeckel** [comment]
**Originally on 2010-03-05 08:14:08 +0100**

___
Fixed in the next nightly build.

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:40:42 +0200**

___
reopened due to upcoming merge on 2.6p1 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:37:49 +0200**

___
In (28c0083):
 * YAM_TR.c: in case an imported mail contains both the Status and the X-Status
  header lines the "new" state of the mail is derived from the Status header
  line only, because the X-Status header line does not contain any explicit
  information about the "new" state. This closes #118.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:38:18 +0200**

___
In (d81f0bc):
 * YAM_TR.c: in case an imported mail contains both the Status and the X-Status
  header lines the "new" state of the mail is derived from the Status header
  line only, because the X-Status header line does not contain any explicit
  information about the "new" state. This closes #118.
