### ISSUE TITLE
Review all function argument to use 'const' if possible.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#129]
**Originally on 2010-03-06 00:40:52 +0100**

___
According to make YAM more secure, especially in upcoming multitasking handling, it would be usefull to review all function arguments of all functions if they may be changed to contain the 'const' qualifier so that the compiler warns in case a change may affect the content of an argument.

**Comment by tboeckel** [comment]
**Originally on 2010-12-18 23:31:52 +0100**

___
From my point of view this ticket is fulfilled. Although the "const" keywords is not used for all functions where it could be used, but I think most functions make use of it whenever it is possible.

If this ticket is to be fulfilled 100% then it will never be closed, because future functions may be implemented without "const" in the first place and thus we would have to reopen this one over and over again.

So better keep in mind to add "const" at as much places as possible. If this forgotten too easily then perhaps this should be noted in the STYLEGUIDE.

Closing this as "works for me", because there is no better suiting description.
