### ISSUE TITLE
Improve Birthday checking

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#138]
**Originally by _opionline@yahoo.de_ on 2010-03-06 05:55:27 +0100**

___
Hi

For users like me who sometimes run YAM without a restart
it might be very important to rework the Birthday checking
function in YAM so that YAM check the birthday if a new day
is beginning. It could be done in the follow way.

At startup remember the current (old) day.
Call AB_CheckBirthdates() (like now).
Calculate the time until the next day (maybe add some seconds).
Run a Birthday timer with the calculated time.

If the timer triggers then check if old day <> current day and
only if both are different then Call AB_CheckBirthdates()

remember the current (nowold) day.
Calculate the time until the next day (maybe add some seconds).
run a Birthday timer with the calculated time.

In this way the user should not get a reminder twice also if
he change the time or date while YAM is running.

The only remaining issue is that we get the reminder one hour to
late if the DST is changed forward but it happen only once a year.

BTW: you should change some comments in Timer.c. Search for "idn"
and change it to "ion"...

**Comment by tboeckel** [comment]
**Originally on 2010-03-10 11:39:43 +0100**

___
In (4003bbf):
 * YAM_AB.c, YAM.c, Timer.c: birthdays are now checked on a regular basis. This
  means that YAM will automatically check for pending birthdays at 00:01 each
  day if it is running over midnight. Let's see what the users think of this.
  Maybe we need a configurable time for this check instead of the fixed 00:01.
  This closes #138.
