### ISSUE TITLE
Keyboard control doesn't highlight correctly

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#14]
**Originally by _hitman@codehq.org_ on 2010-03-03 15:50:14 +0100**

___
A while ago I reported a problem here with keyboard control not working
properly and was advised to update to the latest YAM. I did this and it
seemed to be fixed, but I just realised that it's not. It's easy to
reproduce.

1) Select a message in the list of messages in the right pane.
2) Press shift-tab 4 times to select a foler in the list of folders in the
left pane.
3) Press the up or down arrow key.

You will see the the greyed out highlight in the message pane moves, not
the blue highlight in the folder pane.

This is with the latest YAM nightly build.

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 14:58:00 +0100**

___
Indeed, I am able to reproduce that. It seems we have to invest some more time in checking why with changing the focus via the keyboard doesn't end up in a changed keyboard focus.

**Comment by tboeckel** [comment]
**Originally on 2010-07-29 12:33:32 +0200**

___
In (0869f0a):
 * YAM_MA.c, mui/MainWindow.c, mui/MainMailListGroup.c: the "active object on
  click" feature of NList must operate on listview objects instead of the em-
  bedded list objects. Thus we have to distinguish between these two in lots
  of places. Together with the latest modificiations to NList itself this
  closes #14. The bug is already fixed without the NList modifications, but
  there will still be the annoying active borders because of a limitation of
  the current NList release.

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:29:59 +0200**

___
reopened due to upcoming merge on 2.6p1 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 12:00:29 +0200**

___
In (9369642):
 * tools/mkrelease.sh: copied over the mkrelease.sh script from the 2.7 branch.
  This fixes #14.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 12:35:59 +0200**

___
Reopened because of accidentally wrong closed ticket.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:41:54 +0200**

___
In (a62f27c):
 * YAM_MA.c, mui/MainWindow.c, mui/MainMailListGroup.c: the "active object on
  click" feature of NList must operate on listview objects instead of the em-
  bedded list objects. Thus we have to distinguish between these two in lots
  of places. Together with the latest modificiations to NList itself this
  closes #14.
