### ISSUE TITLE
ARexx help command produce Hits and output trash

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#159]
**Originally by _opionline@yahoo.de_ on 2010-04-19 14:13:18 +0200**

___
As the Summary say ARexx help command produce Hits and output trash.

The cause is that the for loop in rexx/help.c line 68 does not
find the end of the rxs_commandlist.

A possible solution is to terminate the list in Rexx.c like
in the attached patch file so the loop always find the end.

Is it ok if i commit the patch?

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-04-19 14:13:41 +0200**

___
**Attachment added:** [`Rexx.c.diff`](https://yam.ch/attachments/159/Rexx.c.diff) (0.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-04-19 14:23:34 +0200**

___
In (b0575ce):
 * Rexx.c, rexx/help.c: added terminating dummy entry to avoid a crash in the
  ARexx HELP implementation. This closes #159.

**Comment by tboeckel** [comment]
**Originally on 2010-04-19 15:06:50 +0200**

___
Hi Frank! 
I just noticed that you also supplied a patch to fix this bug. It seems I read a bit too fast and fixed the bug faster than reading your report including the patch completely. I really have to appologize for this!

Your patch was exactly the correct thing to do. But there was one little notion missing. YAM uses a binary search for the command lookup which takes the number of array entries as a parameter. The dummy entry must be excluded from this number, otherwise the search would cause other crashes or even refuse certain commands although they exist.

Please continue to contribute patches like this or even commit them directly to the repository. Neither Jens nor me are perfect either and both of us already commited "half" patches.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-04-19 16:04:32 +0200**

___
No problem. The mainpoint is that the bug is fixed. 

I saw the bsearch issue as i view into your patch.
So your full patch is better as my not complete patch. :-)

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:32:02 +0200**

___
reopened due to upcoming merge on 2.6p1 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:05:45 +0200**

___
In (af97058):
 * Rexx.c, rexx/help.c: added terminating dummy entry to avoid a crash in the
  ARexx HELP implementation. This closes #159.
