### ISSUE TITLE
DSI crash when unselected text in mail editor

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#165]
**Originally by _s.hawamdeh@teletu.it_ on 2010-05-22 08:24:35 +0200**

___
I get a DSI crash clicking on unselected text (on mail composer) in WB menu, the text was not selected but the option to unselect still remain, so maybe must be ghosted too when not usable.

Maybe is a TextEditor bug but i'm not sure at 100%

**Comment by jens-maus** [comment]
**Originally on 2010-05-22 08:27:51 +0200**

___
**Attachment added:** [`crashlog.txt`](https://yam.ch/attachments/165/crashlog.txt) (6.8 KiB)
Catched crashog

**Comment by jens-maus** [comment]
**Originally on 2010-05-22 08:29:02 +0200**

___
I moved the crashlog to an attachment. So please next time do not add the crashlog directly to your bugreport message but always submit it as a *.txt attachment to bug items.

**Comment by tboeckel** [comment]
**Originally on 2010-05-23 19:55:15 +0200**

___
I have read this report about ten times by now, but I cannot understand it. What does "WB menu" have to do with either YAM or TextEditor.mcc? I also tried to select some text and click somewhere else and to just click somewhere into the either selected or unselected text without any crash. But I am not sure if that is what you did, simply because I don't understand your description.

So please try to explain a bit better and more verbose how to cause the crash, if it is reproducable at all.

**Comment by tboeckel** [comment]
**Originally on 2010-05-23 20:04:27 +0200**

___
Oh yes, I forgot to ask, which version of TextEditor.mcc are you talking about? The latest release (15.33) or some other version?

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-05-23 20:38:51 +0200**

___
Well first of all i'm using latest YAM 2.7 nighly with MCC TextEditor 15.33 (AmigaOS 4.1 Update 2)

Having said that, this is a (step by step) guide to be able to reproduce this DSI:

- Start YAM :-))
- Go in "incoming" section (mail arrived at the left)
- Now double click on any of this mail arrived in order to open it in a new window
- Now go to the WB menu and select: Edit --> Select none

You don't need to have selected text before, just click on "select none"

This option is always active also if you didn't select any text before.

**Comment by tboeckel** [comment]
**Originally on 2010-05-25 08:12:23 +0200**

___
Fixed in the next release of TextEditor.mcc.
