### ISSUE TITLE
New search/filter not working as expected?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#168]
**Originally by _mario@cattaneo.de_ on 2010-06-04 18:11:00 +0200**

___
I have a filter, looking up "to:" and searching for something like

= #?xxx#?@mydomain.de#?

I expect it to get me anything with "xxx" going to my domain, which it did (and still does in amigados-mode).

When I now change it to something like

= *xxx*@mydomain.de*

in new BoyerMooreSearch it no longer works.

Human (ie. my ;)) error, or something wrong with the new algo?

**Comment by tboeckel** [comment]
**Originally on 2010-06-04 20:37:25 +0200**

___
The Boyer/Moore string search algorithm is a plain search algorithm, not a pattern matching algorithm as you are trying to use it. The main difference to the former implementation is that Boyer/Moore is a *really* fast algorithm compared to some really dumb standard implementations.

So if you want to use patterns like "#?somebody#?@domain.com" you must enable the AmigaDOS patterns switch. Otherwise you will let YAM search for the exact string "#?somebody#?@domain.com" which is very unlikely to occur as a normal address.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-04 21:38:09 +0200**

___
Ok, didn't know that.

Maybe, if not already done, this could be noted somewhere for the non-ITlers among us? :)
