### ISSUE TITLE
clicking on the result of a search opens 2 readwindows

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#187]
**Originally by _opionline@yahoo.de_ on 2010-08-24 22:53:52 +0200**

___
Step by step to reproduce:
1. be sure you set up YAM to use readwindows.
2. go to a folder with some mails.
3. do a search and be sure you get some mazches.
4. double click on a search result.

At this point YAM opens 2 read windows:
1. the active Mail from the mainwindow
2. the selected mail from the search results

YAM should IMHO only open window 2.

used version:
YAM 2.7-dev [OS3/m68k] date 24.08.2010 (build 20100824)

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 08:57:06 +0200**

___
In (567a318):
 * mui/MainMailList.c, YAM_FI.c: the main mail list object can now be told not
  to handle double clicks itself but to let the surrounding stuff handle this
  case. For the mail search window this caused multiple read windows to be
  opened, because the double click in the result list caused the click to be
  handled twice, but the class itself and once again by the search window.
  This closes #187.
