### ISSUE TITLE
previous message in thread requester

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#19]
**Originally by _opionline@yahoo.de_ on 2010-03-03 16:44:36 +0100**

___
if i click on "previous message in thread a requester" pop up and ask "In order to follow the thread, YAM has to load all indices..." with the options Yes and No.

if i click "No" but the index is already loaded then YAM switch to the previous message.

More user friendly would be if YAM first search in loaded indexes for a previous message and only if not found pop up the above mentioned requester.

**Comment by tboeckel** [comment]
**Originally on 2010-12-18 20:34:13 +0100**

___
While reading this ticket again I asked myself the question if loading a flushed/not yet loaded index is really that "expensive" in terms of memory and time that YAM has to ask the user about this.

When outdated mails are to be deleted automatically there is also no question whether to load an index or not. It is loaded to determine which mails are too old and which have to be kept. No matter what.

Since YAM will flush recently unused indices automatically this ticket becomes even worse, because if YAM loaded all indices on startup this might be no longer true after i.e. 30 minutes. YAM also doesn't ask whether to load an index or not if the user changes the current folder. The index will be loaded, because it is needed then.

So my suggestion is to drop that question completely and simply perform the search on all folders. Sooner or later YAM must be able to keep all indices in memory, even if that is for a short time only. And since indices will be flushed automatically there is no reason not to load the indices automatically without acknowledgement from my point of view.

Any objections if we remove that question completely?

**Comment by tboeckel** [comment]
**Originally on 2011-01-05 12:29:58 +0100**

___
Since I got no reply so far I suppose nobody objects if I remove the confirmation requester.

**Comment by tboeckel** [comment]
**Originally on 2011-01-05 12:57:07 +0100**

___
In (9483316):
 * YAM_MA.c, locale/YAM.cd: removed the confirmation requester when a global
  search over all mail folders for a threaded answer has to be performed.
  Since YAM periodically flushes all indices the confirmation is more annoying
  than helpful. See #19 for details. This closes #19.
