### ISSUE TITLE
YAM crash if you click 'abort' in the transfer window.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#192]
**Originally by _opionline@yahoo.de_ on 2010-08-27 15:57:20 +0200**

___
As the Summary say:
YAM crash if you click 'abort' in the transfer window.

Simply try to get mails and if the transfer window is open
then click on 'abort' -> bum...

I attach a logfile with the hits. (MuToolsHits-27.08.2010.txt)
here is no YAM reference in the stack trace but maybe the
file helps to find the cause.

used version:
YAM 2.7-dev [OS3/m68k] (27.08.2010)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-27 15:57:34 +0200**

___
**Attachment added:** [`MuToolsHits-27.08.2010.txt`](https://yam.ch/attachments/192/MuToolsHits-27.08.2010.txt) (10.1 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-08-28 19:37:33 +0200**

___
No matter how often I interrupt an SMTP session I cannot make YAM crash. And I don't need to be very fast because of my crawling slow connection (53.6K/s at most). What makes the search for a potential bug in YAM even harder is the fact that your log doesn't even mention YAM in the stack backtrace, only as current process.

Can you provide a NET+UTIL log please? Perhaps this might enlight us.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-29 03:12:34 +0200**

___
Ok then here some hints to find the bug:
1. You must set a command in config->New mail->Command
(here it's "run >NIL: c:play16 Work:Prefs/Soundprefs/POST.iff")
2. You must at least download one mail.
3. The crash seems to be time critical. E.g. i don't get a crash
if i see the debug output on the outpu window. If i iconify the
debug output window then i get always the crash.
4. The crash happen in the the YAM_UT.c->SyncLaunchCommand()
function at the SystemTags() call. That may explain why here
is no YAM reference in the stack trace. But my knowledge about
the function in NULL. Maybe a tag is missed or wrong!?
5. I attach a file (sashimi.out) with the last debug lines
before the crash and the Hits itself. I redirect the debug
tools output to the same debug console.

HTH


BTW: Do we really need the ENTER() and RETURN() macros in
YAM.c->Root_GlobalDispatcher()? It makes a lot of noise on
the debug console also if YAM is doing nothing. IMHO the macros
makes not much sense here. I know i can disable some output
by setting the yamdebug variable but most i use '@all all'
because it's easier for me and i don't have to remember which
combination in yamdebug i need.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-29 03:12:56 +0200**

___
**Attachment added:** [`sashimi.out`](https://yam.ch/attachments/192/sashimi.out) (20.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-08-29 13:16:33 +0200**

___
In (ec87801):
 * YAM_UT.c: launching a command synchronously with output redirected to the
  current standard input/output channels would crash sooner or later, because
  YAM closed exactly these channels. Now the channels are closed only if YAM
  did open them explicitly before. This closes #192.

**Comment by tboeckel** [comment]
**Originally on 2010-08-29 13:29:59 +0200**

___
Many thanks for this hint.

But if you want to let YAM play a sound after receiving some mails, you should use YAM's own sound playing abilities instead of doing this by using an external command.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-29 23:20:07 +0200**

___
This config entry is very old. Maybe at this time YAM was not able
to play sounds itself!? I don't remember why it is still here...
But with that entry the bug was easier to find. :-)
