### ISSUE TITLE
growing .folders file

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#198]
**Originally by _opionline@yahoo.de_ on 2010-08-31 03:48:59 +0200**

___
Step by step (sorry german strings)

1. Backup your .folders file
2. Go to config and enable config->Spam->'Spam-Filter aktiv'
3. Click 'Benutzen'
4. A requester pop of - i click 'Leeren&Verwenden'
5. Go again to config and disable 'Spam-Filter aktiv'
6. A requester pop of - change all checkboxes to not enabled
7. Click 'Benutzen' in the requester.
8. Maybe you must repead the steps 2-7

Now compare your .folders and you will see that an:

@FOLDER Spam
spam
@ENDFOLDER

is added to the file ecery time you do the steps above 
which should not happen IMHO.

BTW: IMHO the better default values into the requester is
all checkboxes disabled? It need more diskspace for the
Data but if the user want to enable the spam filter again
he need no training the filter from scratch.

**Comment by tboeckel** [comment]
**Originally on 2010-09-01 12:01:16 +0200**

___
In (222642e):
 * YAM_COs.c, YAM_FO.c, FolderList.c: en/disabling the spam filter several
  times without restarting YAM eventually resulted in multiple folders named
  "Spam", because the folder's node was only removed from the listtree, but
  never from the folder list. When trying to remove the folder a second time
  YAM would work with the previous node pointer and hence was not able to find
  this node in the listtree and in turn did not remove the tree node. Now the
  folder is correctly removed from the folder list. This closes #198.
