### ISSUE TITLE
Graphics corruption under AROS

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#205]
**Originally by @mattrust on 2010-09-08 08:05:23 +0200**

___
Moving the horizontal balks in the right window causes graphics corruption. It disappears when I change the size of the window.

**Comment by jens-maus** [comment]
**Originally by @mattrust on 2010-09-08 08:05:47 +0200**

___
**Attachment added:** `yam.png` (21.2 KiB)
![yam.png](https://yam.ch/attachments/205/yam.png)
Screenshot

**Comment by tboeckel** [comment]
**Originally on 2010-09-08 08:28:49 +0200**

___
Does this also happen with YAM 2.6 and the same support classes? If not, then this is a bug we introduced by merging the code. Otherwise we'll have to look into the changes done to the additional MUI classes.

The obvious corruption looks like help bubbles from the folder listtree.

For me the visual corruption does not apply to the TextEditor.mcc instance to display the mail text alone, but also to the scrollbars of the two NList objects. The slider seems to be 2 or 3 pixels too large and partly covers the arrow buttons. Or is this a known issue of Zune?

**Comment by jens-maus** [comment]
**Originally by @mattrust on 2010-09-09 06:36:30 +0200**

___
Replying to thboeckel:
> Does this also happen with YAM 2.6 and the same support classes? If not, then this is a bug we introduced by merging the code. Otherwise we'll have to look into the changes done to the additional MUI classes.

Yes, it happens with 2.6, too. If it doesn't appear in versions for other AmigaOSes it's very likely a bug in Zune.

**Comment by tboeckel** [comment]
**Originally on 2010-09-09 09:47:45 +0200**

___
Ok, I'll close this ticket and mark it as invalid for now. If it should turn out to be not Zune related but a true issue of either YAM or any of the classes then please reopen it.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-09-15 08:34:39 +0200**

___
Replying to thboeckel:
> Does this also happen with YAM 2.6 and the same support classes? If not, then this is a bug we introduced by merging the code. Otherwise we'll have to look into the changes done to the additional MUI classes.

Yes, it happens with 2.6, too. If it doesn't happen with versions for other AmigaOSes it's very likely a bug in Zune.
