### ISSUE TITLE
YAM doesn't show the very first command send to the server.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#213]
**Originally by _opionline@yahoo.de_ on 2010-09-17 16:38:36 +0200**

___
As the Summary say YAM doesn't show the very first command send to the server.

Step by step to reproduce:
1. Start YAM in debug mode.
2. Get mails.
3. The first line in debug output is anything like:

SERVER[0065]: +OK hello from popgate 2.46.7 on pop105.plus.mail.ac4.yahoo.com

I miss here the command YAM was send to the server before the server respond.

**Comment by tboeckel** [comment]
**Originally on 2010-09-19 13:18:36 +0200**

___
There is nothing missing, because nothing has been sent out before.

Look at src/tcp/pop3.c line 312. The first "command" YAM sends to the POP3 server is POPCMD_CONNECT, which is an empty string. Hence nothing is send and there is nothing to print out.

**Comment by tboeckel** [comment]
**Originally on 2010-09-19 13:19:58 +0200**

___
For the 2.6p1 branch this is src/YAM_TR.c line 3231.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-09-23 05:56:09 +0200**

___
Sorry i don't look at the source because i try to test programs
like a DAU. So i see only a 'hello' from the server and think
why does he say hello without i spoke to him?
I was expecting a 'Connect to Server....' or something like that.
