### ISSUE TITLE
Improve error message when attachment loading fails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#225]
**Originally by _mario@cattaneo.de_ on 2010-10-03 13:53:18 +0200**

___
YAM 2.7-dev [OS4/PPC] (02.10.2010) Copyright (C) 2000-2010 YAM Open Source Team

I have set Multiview as default tool if no MIME rule applies.
Now when I double click an attachment that is unrecognized by MV YAM's error requester says:

"Die Ausführung des Kommandos 'SYS:Utilities/Multiview "RAM
Disk:T/YAMm000001cc-p3.mp4"' ist fehlgeschlagen (Fehler
2000: Fehler 2000)."

Whereas the same command in a shell says

"Unbekannter Datentyp bei YAMm000001cc-p3.mp4"

Maybe the returned shell-error could be used in YAM requester, instead of mentioning "error 2000" (twice, btw)?

For now I have "workedarround" this by calling MV with "wbrun", then I get a MV requester complaining. And as YAM is started from WB, too, this looks even more "pro". ;)

**Comment by tboeckel** [comment]
**Originally on 2010-10-03 14:25:29 +0200**

___
Sorry, but there is nothing to fix. YAM already tries to display both, the error number and the corresponding error string. But since error #2000 does not really exist for DOS all to be done is to convert this number to the corresponding error string "error 2000". And this is exactly the error number returned by MultiView. Maybe MV derives this number from datatypes.library, but it is not YAM's task to work around this. The error message you see in the shell is printed by MV itself, not by the shell.

**Comment by tboeckel** [comment]
**Originally on 2010-10-03 14:26:16 +0200**

___
I just forgot, better file an appropriate BZ entry again MultiView in OS4's bugtracker instead.
