### ISSUE TITLE
Perform notifications only when all download-tasks are done

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#229]
**Originally by _mario@cattaneo.de_ on 2010-11-07 13:55:05 +0100**

___
YAM 2.7-dev [OS4/PPC] (06.11.2010) Copyright (C) 2000-2010 YAM Open Source Team

I don't know if this is possible at all, but if so, it would be nice if this could, at least as an option, be implemented.
I have a sound played when new post arrives and now I get this with every pop-tasks that finishes, same with "OS bubbles". I think it it would be enough if there was a "final status update" (with total number of new mails)

**Comment by tboeckel** [comment]
**Originally on 2010-11-08 08:16:31 +0100**

___
I am really sorry, but this is impossible. The completely asynchronous approach of sending and receiving mails also forbid assumptions about when another download may end.

Just imagine a scenario like this. You have one account with lots of huge mails which take about one hour to be downloaded. Then you have a second account with a constant flow of small mails which can be downloaded very quickly. If you start downloading mails from both accounts your proposal would delay showing the notification for the second account for at least one hour. Furthermore, what would YAM be supposed to display as notification if the second account was checked several times within that hour and downloaded some mails each time? Would you like to get as many notifications as YAM did downloads? I really doubt this. Any delaying a summed up notification is no choice either, because you might have read the mails of the second account already in the meantime and the notification would be absolutely useless.
