### ISSUE TITLE
YAM Guide directly accessible via menu

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#258]
**Originally by _s.hawamdeh@teletu.it_ on 2011-03-13 03:57:18 +0100**

___
Would be pretty usefull if YAM would be able to access the YAM's guide directly from WB menu instead of the actual solution when the user needs to open his YAM directory to search and then read it.

Obviously not all language supported by YAM are availible for the YAM's guide, so it would be nice to introduce a dynamical solution, when for example if user use YAM in french language YAM must recognise this and make availible the french one from menu and so on ...

If guide are missed for a particular language used in YAM (for example italian) the quick solution would be open the default guide instead (english)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2011-03-13 07:18:21 +0100**

___
Why not press "Help" on your keyboard or (in my case on a new USB one) "Print" (as there is no "Help" key, i redirected it)

It will open the guide for you (given it has been installed correctly)

It even opens at the part in YAM you currently use, i.e. if you need help in Config, activate that window and press "Help", the configure guide will pop up

It can't get more user-friendly than that

**Comment by tboeckel** [comment]
**Originally on 2011-03-14 10:25:30 +0100**

___
YAM (or better MUI itself, since this is a general feature of MUI) will use a file named "YAM.guide" when the HELP key is pressed and will let amigaguide.library open it. There is no language check or anything similar. If you used the supplied Installer script to install YAM then there will be a file named YAM.guide, which defaults to english language in case no native translation is avaible. It does not matter if the contained language matches your preferred language or not.

**Comment by jens-maus** [comment]
**Originally on 2011-03-14 20:25:36 +0100**

___
Even if Thore already flagged this ticket as invalid and closed it, I thought about the idea of adding a separate menu entry to YAM to explicitly pop up the help guide instead of only solely relying on the HELP key functionality of YAM. And indeed I feel that it would be benefital to have a "Help" menu item somewhere which can be used to bring up the guide.

Thore? opinions?

**Comment by tboeckel** [comment]
**Originally on 2011-03-14 20:54:44 +0100**

___
What's the benefit of having 1001 ways to get to the online help? Or to say it in other words: what is wrong with the HELP key? Having a menu item would just open YAM.guide, but the big advantage of the HELP key is that it works context sensitive, which the menu item cannot come up with.

Convince me why a separate menu item has any advantage over the HELP key and I will implement it. Otherwise things will stay as they are right now.

**Comment by jens-maus** [comment]
**Originally on 2011-03-14 22:34:15 +0100**

___
Well, of course the HELP key does the job perfectly fine (if you know about it). However, for the untrained it might be more intuitive to search through menu items. So this is just a question of user friendliness and not about adding 1001 ways of doing the same. E.g. have a look at how Mac OSX presents its help choices to the user. While there is always the possibility to use the Apple-? hotkey to get help on an application, the menu in ALL applications in OSX carry a "Help" submenu which allows to bring up possibilities to get more information. So yes, IMHO it could be benefitial to have a "Help" submenu item in YAM as well.

In fact, I would even get farther and would propose to have MUI automatically add a "Help" submenut entry for all applications. But as we can't change that for all platforms I would simply suggest to add that possibility at least for YAM!

**Comment by tboeckel** [comment]
**Originally on 2011-03-15 15:56:23 +0100**

___
In (f0fbe59):
 * YAM_MA.c, locale/YAM.cd, locale/german.ct: added a Help menu which contains two items for the main contents and the ARexx interface for now. This closes #258.

**Comment by tboeckel** [comment]
**Originally on 2011-03-15 16:03:23 +0100**

___
One final comment, even if a default Help menu item would be desireable not every MUI application must have a menu, thus this would be impossible to implement. However another title bar button (or a corresponding item in the drop down menu) would be possible, since this is independend of the application.
