### ISSUE TITLE
Window borders overwrittin when window size minimized

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#260]
**Originally by _jeg11@comcast.net_ on 2011-05-16 08:05:42 +0200**

___
## Summary
If the main YAM window is minimized using the window sizing gadget, some of the gadgets cover the window border to produce an ugly effect. Several other users at Amigans.net were able to confirm the problem. Sometimes the same problem occurs when the window is shrunk with the Zoom gadget, but not always. Occasionally the window can be minimized with the sizing gadget without gadgets overhanging the window borders so I would classify the problem as reproducable about 90% of the times window minimizing is attempted.
## Steps to reproduce
 1. Select the main window sizing gadget and drag it inward until the window reaches the minimum possible size.
 2. Simetimes selecting the Zoom gadget to minimize the window produces gadget overhang.
## Expected results
Normal small YAM main window
## Actual results
Corrupted small YAM main window
## Regression
Regression??
## Notes
System: SAM440 Flex 800MZ using OS4.1u2
YAM: 2.6p1 public release

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2011-05-16 09:20:08 +0200**

___
A "Regression" means it worked before and sometime in the past changed behaviour to what you describe.
In a perfect world one could point toward the revision that "breaks" the normal behaviour :-)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-05-19 09:01:25 +0200**

___
Confirmed, this is also a very old and well know issue, hopefully it will be fixed some day

**Comment by tboeckel** [comment]
**Originally on 2012-05-02 09:01:51 +0200**

___
This is definitely an issue of NList.mcc and not of YAM. It seems NList cannot properly decide whether the scrollbars are really needed or not if the window is resized very fast. Resizing the window slowly usually works. Personally I observed this issue myself as well once in while (perhaps once per year). Thus it is quite hard to check if any change to NList really fixes this issue or not.

Until this issue is eventually resolved within NList you might want to configure NList to either always show or never the scrollbars (NListviews -> Scrolling page), at least for YAM if no other MUI application using NList exposes the same issue. Hence I close this bug as "won't fix", because it is no bug of YAM itself.

**Comment by tboeckel** [comment]
**Originally on 2012-05-02 09:23:10 +0200**

___
I must add that I am 99% sure that I just found the true source of this issue. NList was overwriting the width/height values of the superclass with own values which finally made MUI go crazy during the layout process. This means that the next NList release will fix this issue.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2012-05-04 02:50:05 +0200**

___
Excellent, even if not so important for the general usability this is an old issue that i reported years ago so i'me very happy that you finally find the cause :-)
Fell free to send me a new NList beta when and if you need any test !
