### ISSUE TITLE
Change the behaviour after deleting mails.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#28]
**Originally by _opionline@yahoo.de_ on 2010-03-03 17:03:30 +0100**

___
Hi

Currently YAM open the next mail from the message list if i delete a mail in a read window.

I would like if YAM has an option in his config to change that behaviour in (sorry german strings) e.g. in config->Diverses->Speichern/Löschen von Nachrichten and just close the read window instead of open the next mail.

Sometimes it could be very handy to see what the next mail is and if you really want to open such mail now. I don't like to be forced to open another mail only because i delete the currently displayed mail.

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 17:04:07 +0100**

___
What about two different shortcuts for this instead of yet another config option. I'd suggest DEL for the normal (current) deletion of mails and SHIFT+DEL to delete a mail without opening another mail. Maybe the other way round. Although this wont work if one deletes a mail via the toolbar or the menu.

From my point of view a general config option doesn't fullfil the usual needs, that means, sometimes one wants to go to the next mail, but sometimes not. Having two shortcuts for this makes it easier to choose from these two possibilities on-the-fly without having to tamper with the configuration. This would also be more consistent with the current CURSOR and SHIFT+CURSOR behaviour to navigate through the mails.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 17:04:35 +0100**

___
Hm... two different shortcuts for this would be fine but that does not change the behaviour for me because i mostly use the delete button. IMHO the best solution is to add two different shortcuts and 2 config options. the first define the behaviour for the menu and delete button and the second the behaviour for the shortcuts. (open the next mail if the shift button is used or not). In this way we should should be able to satisfy all users.

**Comment by jens-maus** [comment]
**Originally on 2010-03-06 07:11:27 +0100**

___
As this feature seems to be only rarely requested I suggest to add a hidden config option first so that we don't clutter the config GUI with yet another option.

**Comment by tboeckel** [comment]
**Originally on 2010-12-19 07:08:07 +0100**

___
Having though about this one again I must say that I'd like to reject it because of two reasons.

First of all, using SHIFT+DEL instead of DEL is not possible, because SHIFT+DEL is used already to immediately delete mails instead of moving them to the Trash folder, or, in case of the Trash folder, delete the mail completely.

Second, if something like this would be implemented in any way YAM would no longer react consistently. When using the embedded read pane there is always one mail displayed, except the folder is empty. Thus the current behaviour using separate read windows matches the look&feel using the embedded read pane as much as possible with the exception that the read window can be closed. But it is consistent. Deleting the currently displayed mail will show the next mail, with "next" being defined by certain fixed rules.

It is simply impossible to implement something like "do what I mean right now, but do it differently the next time". If YAM has to display a different mail after deleting one this should be consistent and independently of how the mails are being displayed (separate window or embedded read pane). Furthermore using more and more key shortcuts doesn't make your life easier and the next time you hit the wrong shortcut by accident you will curse yourself, because you wanted to get the opposite behaviour.

**Comment by tboeckel** [comment]
**Originally on 2011-01-05 13:01:10 +0100**

___
It seems nobody wants to discuss this topic. Closing it as "won't fix".
