### ISSUE TITLE
DSI-error while writing long e-mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#287]
**Originally by _hotrod_ on 2012-01-27 08:28:10 +0100**

___
I was typing away for a long time (maybe 15 minutes or so) and suddenly I got a DSI-error. Ignoring it worked though and I could finnish typing the e-mail and send it.

**Comment by tboeckel** [comment]
**Originally on 2012-01-27 08:30:08 +0100**

___
Crashlog?

**Comment by tboeckel** [comment]
**Originally on 2012-02-04 19:49:32 +0100**

___
No information from your side means no help from our side. Sorry...

It would be better to get an account here, otherwise you will not be notified about changes to your bug reports. Anonymous reports are still accepted (if they contain some valueable information to fix something), but communication for asking questions is really hard if not impossible then.
