### ISSUE TITLE
YAM not talking path changes for folders?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#296]
**Originally by _mario@cattaneo.de_ on 2012-04-24 16:30:23 +0200**

___
YAM 2.8-dev [OS4/PPC] (16.04.2012)

Not sure, if it's me misunderstanding how YAM works, but...

When I edit a folder (RMB on folder list) and change the path there, YAM does not accept it.
I tried changing Eingang to "RAM:" eg. and it's always set back to $USER/incoming (note $USER stands for the path my mails are in).

I also tried changing $USER/.folders but with every start YAM add this to the end of $USER/.folders

@FOLDER Incoming
incoming
@ENDFOLDER

I also noticed then I open the file requester in "edit folder" the default path shown in the requester is always $USER no matter what the actual path is set to.

Is is all a bit odd to me... :-/

**Comment by tboeckel** [comment]
**Originally on 2012-04-26 08:52:20 +0200**

___
I think you are right. YAM's current handling of changed folder pathes is either wrong or not very intuitive. Looking into this...

**Comment by tboeckel** [comment]
**Originally on 2012-04-26 09:26:53 +0200**

___
In (c3033e8):
 * YAM_FO.c: reworked the handling of modified folders. First of all the folder structure compared in detail now instead of by a general memcmp() which always signals a pending change as even volatile pointers will be compared. Second there were several wrong checks for the new path as only parts of the information were updated. Third a custom folder image was not handled correctly during the move as the image file is locked by the datatypes system and hence has to be released before performing the move. To make it short: moving a folder was broken in several ways. This closes #296.
