### ISSUE TITLE
Hungarian translation for YAM 2.7

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#343]
**Originally by _gmiki_ on 2012-07-26 23:46:14 +0200**

___
Hi,

I have made Hungarian translation for YAM2.7
I updated Dósa Márton s work. You can download from this link:

www.epromirok.hu/downloads/ideigl/YAM.2.7.HUN.catalog.lha

Best Regards
Gmiki
gmiki1@freemail.hu

**Comment by jens-maus** [comment]
**Originally by _gmiki_ on 2012-07-26 23:14:14 +0200**

___
**Attachment added:** [`YAM.2.7.HUN.catalog.lha`](https://yam.ch/attachments/343/YAM.2.7.HUN.catalog.lha) (37.6 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-07-27 06:26:44 +0200**

___
Thanks for your work. But would it be possible to share the .ct file with us instead of the final .catalog file? This would allow us to rebuild the catalog whenever necessary.

Furthermore YAM 2.8-dev has lots of new and updated strings. If you like then grab the updated YAM.cd file, update your translation for YAM 2.8-dev and send the .ct file to us. Your translation will then be included in the nightly build archives.

Finally, opening an enhancement ticket is meant to ask for an enhancement, not to announce it. So better just send your updated translation to either Jens or me in private. So please don't feel offended when I close this ticket as "invalid", as there is nothing to for us :)

**Comment by jens-maus** [comment]
**Originally on 2012-07-30 12:23:59 +0200**

___
Now that the hungarian translation is uptodate and added to the repository we flag this ticket to milestone 2.8 as it will first appear with the next YAM 2.8 release.
