### ISSUE TITLE
Forward complains that there is no message to forward

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#345]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-03 06:48:49 +0200**

___
## Summary

When selecting forward, YAM complains that there is no message to forward even though the message is listed in the attachments section of the write window. I have to delete this entry and add it again.

## Steps to reproduce
 1. Select forward a message
 2. While writing the message, as soon as the message gets saved in "Drafts" the error messages window comes up

## Notes

**Comment by tboeckel** [comment]
**Originally on 2012-08-03 09:58:19 +0200**

___
I was just able to reproduce this myself. The reason is quite simple. When forwarding a mail YAM will remember this process to be able to display a mail a having been forwarded by renaming the corresponding mail file. However, forwarding a mail as an attachment will attach the file **before** renaming it. Hence YAM cannot access the file with the old name anymore and (in)correctly shows an error message.

I will see what I can do about that.

**Comment by tboeckel** [comment]
**Originally on 2012-08-03 10:09:50 +0200**

___
In (d6ebe15):
 * mui/WriteWindow.c: saving a draft mail will not set the "forwarded" flag of forwarded mails as this changes the file name and makes the original mail file inaccessible when eventually saving the outgoing mail. This closes #345.
