### ISSUE TITLE
Attached files are broken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#349]
**Originally by _fernandez_jesus@yahoo.fr_ on 2012-10-04 02:51:03 +0200**

___
## Summary
With the last version 2-8-dev-20120922 (I tested with previous nightly builds too), I have this problem.
If I save the attached files to disk or if I click on it when it is an image, I have an error.
## Steps to reproduce
 1. I sent to myself some attached files.
 2.

## Expected results

The possibility of reading the files. 

## Actual results

The files are broken. For example, the size of an image is reduced from 68k to 4k.
A simple gif : 4k to 7b
An lha archive : 300k to 32k

## Notes
With older nightly build versions (June 2012) and YAM 2.7, this error didn't/doesn't exist.

**Comment by tboeckel** [comment]
**Originally on 2012-10-04 02:55:22 +0200**

___
Please attach some example files and the generated raw mail files.

I just sent a JPEG image to myself and was able to view it from the received mail without problems.

**Comment by jens-maus** [comment]
**Originally by _fernandez_jesus@yahoo.fr_ on 2012-10-04 10:54:17 +0200**

___
**Attachment added:** [`Attach.lha`](https://yam.ch/attachments/349/Attach.lha) (143.3 KiB)
A lha containing the raw message with the broken file and its original version

**Comment by tboeckel** [comment]
**Originally on 2012-10-04 14:04:39 +0200**

___
For me viewing the image works without problems, both by double clicking the attachment icon and by viewing the saved attachment directly.

Please create a "MAIL,MIME" log using the debug version of YAM and attach it to this ticket. There must be something special with your system since I cannot reproduce this issue. Refer to the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities) for details about YAM's debugging facilities.

**Comment by jens-maus** [comment]
**Originally by _fernandez_jesus@yahoo.fr_ on 2012-10-04 15:04:48 +0200**

___
**Attachment added:** [`debuglog.txt`](https://yam.ch/attachments/349/debuglog.txt) (39.3 KiB)
Debug with mail and mime options

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2012-10-04 15:18:32 +0200**

___
I have just the debug log with mail and mime options.
What I did is
1- I launched yam.debug
2- I selected the test email.
3- then I click on the attachment (one jpg file). -> Error message from multiview.
4- Save the file to ram:
5- Close YAM.

**Comment by tboeckel** [comment]
**Originally on 2012-10-05 21:01:26 +0200**

___
It seems you have the "Auto-detect cyrillic charsets" option active on the Read page of YAM's config window? If yes, then please deactivate it. This option is really necessary if and only if you are using the cyrillic charset yourself (i.e. you write mails in russian). Otherwise this options should always be off.

At least with this option active while using "ISO-8859-1+Euro" as read charset I was able to reproduce this issue.

Closing this bug as invalid.

**Comment by tboeckel** [comment]
**Originally on 2012-10-05 21:29:31 +0200**

___
In (33447f1):
 * YAM_RE.c, mime/base64.c, mime/qprintable.c, mime/uucode.c: having the option "automatic cyrillic charset detection" active even without the necessitiy to have to use cyrillic characters will no longer screw up  encoded non-text attachments. This closes #349.
