### ISSUE TITLE
When you click for a message on "hold" the  message disappears but is lost.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#353]
**Originally by _JDuch@fulladsl.be_ on 2012-11-10 12:13:01 +0100**

___
Verified with debug version of  10/12/2012 build/
Nothing much i can add to the title. There is no crash or error message.
I did remark a new folder "hold" was added tot the yam folders, but it is empty

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-11-10 12:15:45 +0100**

___
Oh yes, when closing Yam and restarting, the message was not recuperated neither

**Comment by tboeckel** [comment]
**Originally on 2012-11-10 14:17:22 +0100**

___
Please try to reproduce this isse with the latest nightly build instead of a version which is almost 4 weeks old by now.

Did you try to rebuild the index of the "Drafts" folder (this is its true name, not "hold") to make sure the displayed contents really match the directory contents? Did you check if the folder's directory contains other files than ".fconfig" and ".index"?

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-11-10 20:46:29 +0100**

___
Results with 11/08/2012 version
- the message for which i used the hold button now indeed is to be found in "Drafts"
I previously noted the existence of that folder, and in it i was surprised to find messages in different 'versions' 
- I did not understand the use of it
- I did not create the Hold folder 

How are the 3 folders (to be) used (Hodl, Draft Outgoing) ?

**Comment by tboeckel** [comment]
**Originally on 2012-11-11 22:36:42 +0100**

___
Replying to JosDuchIt:

> I previously noted the existence of that folder, and in it i was surprised to find messages in different 'versions' 
> - I did not understand the use of it

YAM automatically creates all standard folders if they don't yet exist. Thus the first nightly build which introduced the Drafts folder would create this folder.

> - I did not create the Hold folder 
> 
> How are the 3 folders (to be) used (Hodl, Draft Outgoing) ?

There is no folder named "Hold" unless you created one with this name yourself. The Outgoing folder contains mails which are ready to be sent. The Drafts folder contains mails, which are not yet ready to be sent, i.e. you plan to change the mails' contents before finally sending them off.

Before such draft mails were put into the Outgoing folder and would only be sent when their state was changed from "hold" to "queued". But since every other mail application offers a special folder for not yet finished and automatically saved mails we decided to implement something like this in YAM as well. Along with this change the automatic save process has been enhanced not only save the mail's body text, but the complete mail.

So from my point of view there is no bug at all. If you think this is wrong then please reopen this ticket and provide some facts about a true bug.
