### ISSUE TITLE
New Mails are not changed to 'unread' after start of YAM

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#367]
**Originally by _immomdv@gmx.de_ on 2013-01-05 17:32:56 +0100**

___
If a newly received mail is moved to another folder (by hand or by (spam)filter), it will not be marked as 'unread' after the next start of YAM but will still have the status 'new': Only if the mail is in the incoming folder it will marked as unread (check mark 'mark new mail as unread at start' is set).
I have tested this behavior under MorphOS with V2.8 and nightly build.

**Comment by tboeckel** [comment]
**Originally on 2013-01-07 10:19:00 +0100**

___
I just tested this with the current nightly OS3 build and the release version and for me this is working as expected. Any "new" mail in the Spam folder will be marked as unread upon (re)starting YAM.

**Comment by tboeckel** [comment]
**Originally on 2013-01-14 10:21:45 +0100**

___
Any news on this issue?

**Comment by jens-maus** [comment]
**Originally by _immomdv@gmx.de_ on 2013-01-15 00:42:54 +0100**

___
Sorry I was a bit busy the last days. I did this test:
1. Install YAM 2.7 and 2.8 into 2 sepearte directories.
2. Delete .index in both spam folders and copy a 'new' message to both folders.
3. Start YAM 2.7, add 'unread' and 'new' to 'Postfachliste' and in settings remove checkmark of Look & Feel:Eingebettetes Nachrichtenobjekt im Hauptfenster
4. Klick onto the spam folder. **You'll get 1 unread and 0 new messages.** Close YAM2.7
3. Start YAM 2.8, add 'unread' and 'new' to 'Postfachliste' and in settings remove checkmark of Look & Feel:Hauptfenster/Eingebettetes Nachrichtenobjekt im Hauptfenster
5. Klick onto the spam folder. **You'll get 1 unread message wich is also marked new.**

I did my test with MorphOS 3.1. I hope you can reproduce the behaviour with AmigaOS

**Comment by tboeckel** [comment]
**Originally on 2013-01-15 08:58:22 +0100**

___
Replying to immomdv:
> I did my test with MorphOS 3.1. I hope you can reproduce the behaviour with AmigaOS

Repeating these steps still correctly results in one "unread" message in the spam folder for me, even if it was "new" before.

Please provide a FOLDER debug log created with the next nightly build of YAM 2.9-dev. Details about how to create this log can be found in the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities).

**Comment by tboeckel** [comment]
**Originally on 2013-01-15 09:08:13 +0100**

___
Replying to thboeckel:
> Replying to immomdv:
> > I did my test with MorphOS 3.1. I hope you can reproduce the behaviour with AmigaOS
> 
> Repeating these steps still correctly results in one "unread" message in the spam folder for me, even if it was "new" before.
> 
> Please provide a FOLDER debug log created with the next nightly build of YAM 2.9-dev. Details about how to create this log can be found in the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities).

I just forgot to tell, please also provide the subject of the "new" mail as the debug log will list the subject of the mails of which the status is changed while starting up YAM.

**Comment by jens-maus** [comment]
**Originally by _immomdv@gmx.de_ on 2013-01-15 23:55:21 +0100**

___
**Attachment added:** [`debug.log`](https://yam.ch/attachments/367/debug.log) (769.0 KiB)
Debug-Log of comment #9

**Comment by jens-maus** [comment]
**Originally by _immomdv@gmx.de_ on 2013-01-15 23:56:21 +0100**

___
**Attachment added:** [`QemTHwABzUY=.001,N`](https://yam.ch/attachments/367/QemTHwABzUY=.001,N) (0.9 KiB)
'Neue Mail' of comment #9

**Comment by jens-maus** [comment]
**Originally by _immomdv@gmx.de_ on 2013-01-15 23:56:58 +0100**

___
**Attachment added:** [`QemZVQAJnaU=.001,N`](https://yam.ch/attachments/367/QemZVQAJnaU=.001,N) (0.9 KiB)
'keine Neue Mail' of comment #9

**Comment by jens-maus** [comment]
**Originally by _immomdv@gmx.de_ on 2013-01-15 23:58:55 +0100**

___
Replying to thboeckel:
> > Repeating these steps still correctly results in one "unread" message in the spam folder for me, even if it was "new" before.
> > 
> > Please provide a FOLDER debug log created with the next nightly build of YAM 2.9-dev. Details about how to create this log can be found in the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities).
> 
> I just forgot to tell, please also provide the subject of the "new" mail as the debug log will list the subject of the mails of which the status is changed while starting up YAM.

Here is what I did:
I unpacked YAM29dev to RAM: started it once to change Look&Feel:Main window/Show embedded read pane in main window. Then I closed YAM, deleted .index in the incoming folder, copied the file of mail 'keine Neue Mail' into the incoming folder and the file of mail 'Neue Mail' into the spam folder, entered the command setenv yamdebug folder,@all,stdout and then started YAM with yam.debug DEBUG >T:debug.log
Then I enabled the view of unread and new mails and saw 1 unread but no new mail in both the incoming and the spam folder. **After clicking onto the spam folder, I saw 1 unread and new mail.** Finally I closed YAM.

**Comment by tboeckel** [comment]
**Originally on 2013-01-16 09:33:23 +0100**

___
Replying to immomdv:
> I unpacked YAM29dev to RAM: started it once to change Look&Feel:Main window/Show embedded read pane in main window. Then I closed YAM, deleted .index in the incoming folder, copied the file of mail 'keine Neue Mail' into the incoming folder and the file of mail 'Neue Mail' into the spam folder, entered the command setenv yamdebug folder,@all,stdout and then started YAM with yam.debug DEBUG >T:debug.log
> Then I enabled the view of unread and new mails and saw 1 unread but no new mail in both the incoming and the spam folder. **After clicking onto the spam folder, I saw 1 unread and new mail.** Finally I closed YAM.

Now I finally understand what is going wrong here, and what is not. Let me explain.

The startup option "mark new mails as unread" can only be applied to folders for which the index is loaded during the startup phase. By default the option to load the index of all folders is inactive to save time and memory. Thus YAM will skip the "mark new mails as unread" for all folders except the current one, which will be the incoming folder by default. Hence its index will always be loaded and new mails in the incoming folder will become unread. This is something which had to be changed in YAM 2.8, because 2.8 will flush the folder's index from time to time to save memory for seldom accessed folder with lots of mails. And reloading a formerly flushed index should not remove the "new" state of mails. This is why YAM 2.7 behaves differently here.

To solve this issue we now have two possibilities:
1. enable the "load all folders" option on the Startup/Quit page of the configuration
2. enable the "load all folders" option in the default configuration and make the "mark new mails as unread" a suboption of this, as this feature depends on the former one to work as expected in all cases. Furthermore both options should be enabled in the default configuration.

Solution 1 is versy easy to archive even without having to change anything in YAM, except the configuration.

But on the long sight solution 2 seems to be more logical to me. Jens what do you think?

**Comment by jens-maus** [comment]
**Originally on 2013-01-16 12:20:27 +0100**

___
In (f4225d7):
 * YAM.c, YAM_MAf.c: when having the option active that new mail will be changed
  to unread upon restarting YAM, all mails of folders known to carry new mail
  (upon checking the index meta data) will now be changed to unread by forcing
  a full index load via MA_GetIndex(). This partly addresses and refs #367.

**Comment by tboeckel** [comment]
**Originally on 2013-01-16 16:35:42 +0100**

___
Jens' latest change fixes this issue, at least all my tests resulted in the correct behaviour. Please try yourself with the next nightly build and reopen this ticket if you still think there is something wrong.

Please note, "next nighlty build" always denotes the binary built in the next upcoming night, which is usually on the next day (tomorrow) around 2:00 CET in the morning. I am just mentioning this fact, because your debug log was done before the next nightly build was released.

**Comment by jens-maus** [comment]
**Originally on 2013-07-02 21:18:45 +0200**

___
**Release Note:**
fixed a bug where 'new' mail was never changed to 'unread' status if it was moved to a subfolder. Now the index of all folders carrying 'new' mail will be loaded and the status adapted accordingly.
