### ISSUE TITLE
Duplication of emails in Drafts.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#375]
**Originally by _lee@hawke.free-online.co.uk_ on 2013-01-16 17:53:45 +0100**

___
AmigaONE XE / OS4.1u6 / YAM 2.9 dev 15/01/2013 (GCC 4.7.1, r6514).

Open an email in the "Outgoing" folder and click "Hold", this creates a duplicate email in the "Drafts" folder. Everytime you do this, another duplicate will be created in "Drafts".

Surely, the email should be MOVED from "Outgoing" into "Drafts" when the "Hold" button is clicked rather than COPIED? Similar to when you create an email in "Drafts" and click "Send later" ?

**Comment by jens-maus** [comment]
**Originally on 2013-01-16 20:34:01 +0100**

___
Would you please refrain from modifying ticket properties. It is up to the developers to decide to which milestone a ticket belongs.

**Comment by tboeckel** [comment]
**Originally on 2013-01-17 16:12:14 +0100**

___
Your objection is a good one. But Jens and me just had a longer discussion about this situation and we came to the conclusion that moving a mail from Outgoing to Drafts before editing it again is no viable solution either. The point is that immediately after the move one could click on "Cancel". What should happen to the mail then? Leaving it in Drafts is wrong, because it should be in Outgoing again, because canceling something should restore the former situation? But what if the mail has been modified and saved automatically in the meantime? Moving the mail back to Outgoing would not restore the former mail. It would be a different one.

We finally came to this conclusion. Double clicking a mail in Outgoing will no longer open an edit window, but will simply just show this mail as for any other type of folder. Currently we already have the menu items "Edit as new" and "Change/Modify", but right now the situation in which they are available is wrong: "Edit as new" appears for the Drafts folder and "Change/Modify" appears for the the Outgoing folder. This must be swapped. Furthermore the write window's "Hold" button should be renamed to "Save" and leave the write window open when clicked. Thus choosing "Edit as new" in Outgoing will leave the mail as it is and start editing a **new** mail with the same content. Sending this new mail (either immediately or later) will create another mail in Outgoing. The user will have to delete the old mail from Outgoing manually. However, this ensures that clicking "Cancel" will have the desired and correct effect, no matter when this is done. Finally the philosophy for Outgoing is slightly changed in such a way that Outgoing really contains mails only which are considered "finished". Finished things should not be modified anymore, otherwise they could not have been "finished" in the first place. "Unfinished" stuff belongs to Drafts, as the name suggests.

Although this means a break in YAM's known behaviour we think that this changed behaviour makes YAM more consistent.

**Comment by tboeckel** [comment]
**Originally on 2013-01-17 16:50:00 +0100**

___
In (48941ba):
 * YAM_MA.c, YAM_WR.c, mui/MainMailList.c, mui/ReadWindow.c: swapped the edit menu item titles for the Drafts and Outgoing folders. Mails in drafts can be edited directly and mails in Outgoing can only be edited "as new" like in any other folder. This partly addresses and refs #375.

**Comment by tboeckel** [comment]
**Originally on 2013-01-17 20:10:22 +0100**

___
In (eb6b420):
 * misc: removed all references to the old HOLD and QUEUED states. These states are now implied by a mail's folder (Drafts or Outgoing). This refs #375.

**Comment by tboeckel** [comment]
**Originally on 2013-01-18 13:56:19 +0100**

___
In (d09d4f4):
 * mui/WriteWindow.c: renamed the "Hold" button/menu item to "Save as draft" as this is what these objects really do. Furthermore the write window is no longer closed in this situation, because saving a mail as draft means that the mail is not yet finished and the user might want to continue to work on it immediately. Finally the Cancel button has been removed as canceling the edit action can be done by closing the window or choosing "Close" from the menu or by pressing the window close key (usually ESC). This finally closes #375.

**Comment by jens-maus** [comment]
**Originally on 2013-07-03 20:50:02 +0200**

___
**Release Note:**
fixed some problems with the new Drafts folder managment where emails could end up duplicated. In addition, the 'Hold' button has been renamed to 'Save to Drafts' to better differentate between the operations.
