### ISSUE TITLE
Drafts Highlight

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#388]
**Originally by _lee@hawke.free-online.co.uk_ on 2013-02-23 14:05:03 +0100**

___
AmigaONE XE/G4 - OS4.1u6 - YAM 2.9-dev [OS4/PPC]  19/02/2013 (GCC 4.7.1, r6588)

When editing the last email in the drafts folder (bottom of the list), click Save as draft, the highlight will move up one line in the main window.

**Comment by tboeckel** [comment]
**Originally on 2013-02-24 12:22:01 +0100**

___
This most probably happens because saving a mail in Drafts a second time will first remove the former version and hence will let the cursor move up. After that the new version will be saved, but the cursor is left on the now different entry. This should be easy to fix.

**Comment by tboeckel** [comment]
**Originally on 2013-02-25 06:33:55 +0100**

___
In (0eba14e):
 * mui/WriteWindow.c: repeatedly saving a mail in the Drafts folder will make  the new mail the active one in case the to be saved mail was the active one before. This closes #388.

**Comment by tboeckel** [comment]
**Originally on 2013-03-05 20:21:17 +0100**

___
In (499b665):
 * YAM_UT.c, mui/WriteWindow.c: added a special function to replace an already existing mail in the drafts folder which makes it a lot easier to keep the currently active mail active. This refs #388.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:42:16 +0200**

___
**Release Note:**
fixed a bug where resaving a mail in the drafts folder caused the mail active/inactive state to get messed up.
