### ISSUE TITLE
Crash while aborting remote filtering

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#390]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-04 15:16:38 +0100**

___
Hello. Was testing and just getting a remote filter working. But it was taking too long communicating with mail server and sending data back or forth. So I pressed Abort.

First YAM told me the mail server reported some error about the QUIT comand and it spewed back some unreadable text. Looked like MIME format.

YAM then crashed. Let it run again. Crashed. Tried to ignore DSIs and let it recover. Too far gone, YAM froze, and I had to reboot. But ti did manage to put the preview window up with a corrupted list of items. Looked like random memory in strings.

YAM 2.8 (24/12/2012)
Copyright (C) 2000-2012 YAM Open Source Team [OS4/PPC, r6476]

NList.mcc 20.134 (22/12/2012)

muimaster.library 20.2347 (20/01/2013)
(c) 1992-2010 Stefan Stuntz, et al. [AmigaOS4/PPC] [svn r2394]

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-04 15:17:45 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-03-05_00-42-46.txt`](https://yam.ch/attachments/390/Crashlog_YAM_2013-03-05_00-42-46.txt) (32.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-04 15:18:10 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-03-05_00-42-58.txt`](https://yam.ch/attachments/390/Crashlog_YAM_2013-03-05_00-42-58.txt) (32.5 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-03-04 16:35:09 +0100**

___
In (bbcb256):
 * tcp/pop3.c: remote filters are now applied when getting the single message details. This makes it possible to let the filters check all available information but it also requires the user to wait until the details of all new mails have been received. Otherwise it might happen that some mails will be received although they should be filtered out. This closes #390.

**Comment by tboeckel** [comment]
**Originally on 2013-03-04 16:47:49 +0100**

___
Please check again with the next nightly build. Unfortunately I was not able to reproduce any crashes, hence I am not 100% sure whether these are fixed as well or not.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-08 14:57:41 +0100**

___
Okay checked with 2.9 debug R6608 and the problem still persists.However this time the Selection window pops up over the Transfer window. The Selection window shows no sign of remote filtering or results as it lists each new mail. 

Pressed abort in Transfer window and it crashed. Collected five logs.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-08 15:04:21 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-03-07_00-29-04.txt`](https://yam.ch/attachments/390/Crashlog_YAM.debug_2013-03-07_00-29-04.txt) (35.2 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-08 15:04:49 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-03-07_00-29-47.txt`](https://yam.ch/attachments/390/Crashlog_YAM.debug_2013-03-07_00-29-47.txt) (35.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-08 15:05:13 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-03-07_00-31-32.txt`](https://yam.ch/attachments/390/Crashlog_YAM.debug_2013-03-07_00-31-32.txt) (35.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-08 15:05:39 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-03-07_00-32-14.txt`](https://yam.ch/attachments/390/Crashlog_YAM.debug_2013-03-07_00-32-14.txt) (36.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-03-08 15:06:21 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-03-07_00-32-38.txt`](https://yam.ch/attachments/390/Crashlog_YAM.debug_2013-03-07_00-32-38.txt) (36.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-03-08 20:30:24 +0100**

___
In (29502f6):
 * mui/TransferMailList.c: added some NULL checks to fix #390 again.

**Comment by tboeckel** [comment]
**Originally on 2013-03-08 20:49:34 +0100**

___
Replying to hypex:
> Okay checked with 2.9 debug R6608 and the problem still persists.However this time the Selection window pops up over the Transfer window. The Selection window shows no sign of remote filtering or results as it lists each new mail. 

Unfortunately I am still not able to reproduce the crashes myself. But according to the crashlogs thereis a NULL access happening. This will be fixed in the next release.

Let me explain how remote filters work. Usually all new mails on the server will be marked as "to be downloaded" and "to be deleted" (unless the "delete mail on server" option is disabled). Remote filter can invert exactly these two flags and hence cause mails to be not downloaded or to be deleted. The filter will be applied when YAM has received the single mail details (sender, subject, etc). You will only notice the effect of the remote filter if it really did change one of the two flags.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:51:00 +0200**

___
**Release Note:**
modifiered remote filters to be applied when getting the single message details. This makes it possible to let the filters check all available information but it also requires the user to wait until the details of all new mails have been received. Otherwise it could have happened that some mails were not received although they should be filtered out.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-07-19 17:36:31 +0200**

___
Well that covers what I want, if I understand correctly, for my filter to leave certain emails on the server. I'll do some more testing.
