### ISSUE TITLE
Cursor not remaining on selected folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#391]
**Originally by _lee@hawke.free-online.co.uk_ on 2013-03-05 01:16:56 +0100**

___
2.9-dev [OS4/PPC],  03/03/2013 (GCC 4.7.1, r6600),  AmigaONE XE/G4, OS4.1u6

In Configuration/Look & Feel/General settings - if "Double click on folder opens folder settings" is checked, the following behaviour occurs;

Double click a folder to open the "Folder settings" window, now close it again with the close gadget, the cursor highlight changes position up the list of folders and does not remain on the highlighted folder.

If, however,  you highlight the folder and go to Menu - Folder/Edit... to open the Folder Settings window, closing the window by the close gadget does not have the same action as above, and behaves correctly - the cursor highlight staying put on the selected folder.

**Comment by tboeckel** [comment]
**Originally on 2013-03-06 15:32:51 +0100**

___
This issue will be fixed with the next NList release. NList does some very strange and obscure things during its event handling which in turn causes exactly this effect to happen and hence cannot be fixed in YAM directly. The "fix" was to comment out 2 lines in the NList source. I hope this doesn't break any other software as the NList source comes with next to no comments and is really hard to understand (if at all...).
