### ISSUE TITLE
Identities mixup problem (YAM 2.8p1, MorphOS)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#402]
**Originally by _yam.asc@schwarzes.net_ on 2013-07-09 11:20:13 +0200**

___
This is a splitup related to ticket 401 (part 2). 

Let's assume, I've two  identities, Mr.A @ mydomain.com and Mrs.B @ mydomain.com. Let's also 
assume, Mrs.B is on holiday and is sending an email to Mr.A (which is using yam). If Mr.A now 
answering to the email from Mrs.B, yam uses the identity of Mrs.B for the reply (and not Mr.A,
which would be correct).

**Comment by tboeckel** [comment]
**Originally on 2013-07-09 16:23:02 +0200**

___
So far I am still not able to reproduce this issue myself.

Please create a MAIL debug log using the debug version of YAM while reproducing the issue and attach it here. I suppose replying to the mail is enough to trigger the bug, correct?

**Comment by jens-maus** [comment]
**Originally by _yam.asc@schwarzes.net_ on 2013-07-10 00:36:07 +0200**

___
Ok, I've created full debug log (all) starting with pressing the reply button. It contains the wrong identity selection, but I don't want to put this to the public, because it contains private information like email addresses, etc. and I don't want to anonymise them, because they are important for this bug. So it's better when you tell me an email address where I can send the log.

Btw, when looking to the log, the first match seems 

00:D:    YAM_MAf.c:2374:finduinByAddr: 'Some.Name@somedomain.com' 247da8e4

Seems, that you first check the "mail->From.Address" (line 2374) before "mail->To.Address" (later in line 2495), at this time email->identity is already defined.

**Comment by tboeckel** [comment]
**Originally on 2013-07-10 08:18:45 +0200**

___
Replying to DrB:
> Btw, when looking to the log, the first match seems 
> 
> 00:D:    YAM_MAf.c:2374:finduinByAddr: 'Some.Name@somedomain.com' 247da8e4
> 
> Seems, that you first check the "mail->From.Address" (line 2374) before "mail->To.Address" (later in line 2495), at this time email->identity is already defined.

That was the hint I was looking for! You are right. YAM catches the first matching address as user identity. The point is that the header lines may appear in arbitrary order and hence the wrong identity might be used.

**Comment by tboeckel** [comment]
**Originally on 2013-07-10 08:24:07 +0200**

___
In (210bdae):
 * YAM_MAf.c: while doing a deep examination of a mail YAM will no longer use the first matching address as the mail's user identity but collect all possibly matching identities at first, because the header lines can appear in arbitrary order and hence it is unpredictable which header line eventually produces the used identity. After scanning all headers the identity will be chosen in a predicatable way which prefers the "receiving" addresses. This closes #402.

**Comment by tboeckel** [comment]
**Originally on 2013-07-10 08:24:42 +0200**

___
**Release Note:**
While doing a deep examination of a mail YAM will no longer use the first matching address as the mail's user identity but collect all possibly matching identities at first, because the header lines can appear in arbitrary order and hence it is unpredictable which header line eventually produces the used identity. After scanning all headers the identity will be chosen in a predicatable way which prefers the "receiving" addresses.

**Comment by tboeckel** [comment]
**Originally on 2013-07-10 08:39:53 +0200**

___
**Release Note:**
Fixed a bug which caused YAM to use the first matching address of a mail as user identity even if this address was the sending instead of the receiving one.
