### ISSUE TITLE
folders lose their index

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#436]
**Originally by _hpollmeier@dhps.de_ on 2013-10-01 07:34:57 +0200**

___
Since version of 2.9 as of 28.9. about a quarter of folder indexes get lost.
This is especially bad, when the incoming or spam folders are hit. all mails can be seen again by reindexing the folder. But after a restart the indices are gone again. In my case, 10 out of 40 folders are hit by this bug.

**Comment by tboeckel** [comment]
**Originally on 2013-10-01 07:40:21 +0200**

___
Is it always the same range of affected folders or are the folders random? I really have no clue why this should be happening, because you seem to be to only one with this problem and nothing has been changed in folder index handling since Jens' change to save the folder index as UTF8 on September 16th.

Anyway, a FOLDER log created with the debug version should reveal why the index of some folders gets lost. Please attach that to this ticket.

**Comment by tboeckel** [comment]
**Originally on 2013-10-06 20:06:51 +0200**

___
Is this still happening?

**Comment by tboeckel** [comment]
**Originally on 2013-10-08 12:19:37 +0200**

___
Heiko finally told me that he switched the local charset to UTF8. Switching back to ISO-8859-1 fixed the issue.

The reason is that saving the index assumed a charset different from UTF8 such that a real conversion to UTF8 happens. Upon loading the index again a conversion from UTF8 to the local charset is performed which in turn fails, because the saved index was no correct UTF8.

The solution is to convert the index from UTF8 to the system charset instead of the default local charset and vice versa.

**Comment by tboeckel** [comment]
**Originally on 2013-10-08 20:43:03 +0200**

___
In (2914340):
 * YAM_MAf.c, Config.c: the folder index is converted from the more or less fixed system charset rather than the configurable local charset to UTF8. This avoids corrupted index files in case a user chose UTF8 as local charset, because in this case no conversion happens and non-ASCII characters are not converted to UTF8 and let the index loading process fail due to false conversions. This closes #436.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:43:28 +0100**

___
**Release Note:**
fixed a problem where index files were getting corrupted because of an incorrect UTF-8 support.
