### ISSUE TITLE
Fail to login your site with OWB, cannot commit new Finnish catalog!

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#439]
**Originally by _marko.raina@fimnet.fi_ on 2013-10-08 05:57:48 +0200**

___
## Summary
I have created a new Finnish catalog translation for YAM 2.8 but I cannot commit it to SVN because I don't have a password for that. And OWB fails to Login to your site 
(certificate problem) so this was the only way I could try to reach you. Help!
## Steps to reproduce
 1.
 2.

## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-10-08 06:01:47 +0200**

___
First of all, you cannot commit anything to the repository until we grant you write access. And that requires a valid login on yam.ch.

If all that fails you still can send the updated translation to either Jens or me (tboeckel@gmx.de) privately. We will commit it then. Updated translations are always welcome. So, if possible it would be nice if you would update your finnish translation to the current state of YAM 2.9-dev, because there will be no further update for YAM 2.8 and YAM 2.9-dev got several new strings to be translated.

**Comment by tboeckel** [comment]
**Originally on 2013-10-08 20:28:42 +0200**

___
Closing this, because we have an updated finnish translation now. Many thanks to Marko!

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:48:07 +0100**

___
**Release Note:**
added a fresh and updated finnish translation/catalog to YAM.
