### ISSUE TITLE
Crash when creating new folder (too hastily)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#448]
**Originally by _JDuch@fulladsl.be_ on 2013-11-07 16:06:25 +0100**

___
## Summary
When you create a new folder you are confronted with 2 textin gadgets to enter the display name and the Folder name
When the "dispay name" field is entered, this input is duplicated in the second field "Folder Name" 
Previously say with 2.8 you had to enter the name yourself, or use the possibility to select the folder with a requester. First time users of 2.9 will often  not see the folder name is (slightly) ghosted and go on clicking on the OK button.
A crash will occur

## Steps to reproduce
 1. Open the "dossier/nouveaudossier menu 
 2. Select your type of folder eg "interne" (default)
3. enter your display name in foirst textin gadget
4 Hit theOK button 

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-07 16:10:58 +0100**

___
**Attachment added:** [`crashlogFolder`](https://yam.ch/attachments/448/crashlogFolder) (4.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 16:15:48 +0100**

___
Sorry, but you attached a Snoopy log, not a real crash log created by the GrimReaper. The Snoopy log is useless. It cannot contain any crash related information.

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 16:26:30 +0100**

___
What "ghosted" string object are you refering to? There is nothing ghosted or disabled in the folder edit window, except the mailing list objects at the bottom until you enable the mailing list support.

The "Folder name" string has slightly different colors, because it is **not** the active object, just like the "max age" string object or any other string object. For the "Welcome" and "Closing" phrase string objects the difference might not be noticed that easily as they are empty by default.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-11-07 18:15:47 +0100**

___
**Attachment added:** [`Crashlog_YAM.debg_2013-11-07_11-15-14.txt`](https://yam.ch/attachments/448/Crashlog_YAM.debg_2013-11-07_11-15-14.txt) (34.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-16 23:19:49 +0100**

___
Have you been able to reproduce this issue? For me adding and removing folders works perfectly, even if the config or the search window is open. I mention the additional windows, because these are using object which get update whenever the folder tree is changed. And your crash log is pointing to the folder tree refresh method at some point.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-17 09:05:57 +0100**

___
I have been able to do that a number of times. 
I now retested with NB 13/11 and 17/11 and they work very well, you can even after having typed in a new name with no return, go straight to the OK button: no crash & folder is created.
Ticket can be closed for me
