### ISSUE TITLE
YAM NB 17/11/2013 overrwrites filter settings

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#451]
**Originally by _JDuch@fulladsl.be_ on 2013-11-17 11:58:29 +0100**

___
## Summary
When copying the archive over the existing install, all action contentof the filters is set to
FI02.RedirectTo     = 
FI02.ForwardTo      = 
FI02.ReplyFile      = 
FI02.ExecuteCmd     = 
FI02.PlaySound      = 
FI02.MoveToFolderID = 00000000

## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-17 12:54:51 +0100**

___
I copied from a correct .configOK to .config
Launched YAM
Hit the "filter" button
the same error message appears telling me some masg in the incoming file could not be moved to a non identifie'd drawer
verified the content of .config
It had overwritten the filter actions again.

**Comment by tboeckel** [comment]
**Originally on 2013-11-17 19:23:46 +0100**

___
Please restore the old and working .config file again and capture a CONFIG FILTER FOLDER log using the debug version. This should reveal why the folders are not resolved correctly.

Please keep the old and working .config file until this issue is solved.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-17 19:39:58 +0100**

___
I  always use 2.9Dev in debug version
Can you explaine "capture a CONFIG FILTERR FOLDERR" ?

**Comment by tboeckel** [comment]
**Originally on 2013-11-17 20:19:46 +0100**

___
Replying to JosDuchIt:
> I  always use 2.9Dev in debug version
> Can you explaine "capture a CONFIG FILTERR FOLDERR" ?

Type this in a shell before running YAM:
setenv yamdebug config filter folder file:t:yamlog

This will produce the log file in "t:yamlog"

Please attach that log here afterwards.

Details about YAM's debugging facilities can be found in the [FAQ](https://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities).

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-17 21:21:59 +0100**

___
Forgot to use the correct .config file before making the test asked for.
It will have to wait till tomorrow, just got visitors.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-18 08:46:34 +0100**

___
copied the correct .config file
no get messages,

no new messages that needed to be moved (at least i did not note filterint)
hit the filter button
17 messages moved 
Yamlog2 uploaded

**Comment by tboeckel** [comment]
**Originally on 2013-11-18 20:21:49 +0100**

___
There are some oddities with you configuration.

1. Your folders have localized names (i.e. Reçus, Envoyés) but your user identities refer to the english names (i.e. Incoming, Sent). This difference is most likely caused by the nightly build 2013-11-15, because I changed YAM to use the translated names instead of the english ones later on that day. Please check your POP3 and SMTP server as well as your user identities to reference existing Incoming and Sent folders.

2. Two of your filters, namely "Jée" and "Duch" reference non-existing folders. For example the filter "Duch" should move mails to the folder "JDuch", but that one doesn't exist as can easily be seen from the list of folders been loaded right before the check. However, a folder named "Duch" does exist.

3. For the filter "Jée" things are even worse. There exists a folder named "JÃ©e" which seems to be the UTF8 encoding of "Jée". I cannot tell how you managed to type that name, but since UTF8 is not yet supported by any version of AmigaOS such a name is not going to work. Additionally, although both names are essentially equal they are different due to the different encoding and the different length (3 characters vs. 4 characters).

4. There are still some filters with empty match strings for some rules. Although such rules don't cause any harm they are absolutely redundant and will never cause a filter to match and to perform its actions. The filters with such no-op rules are named "SPAM", "Guy" and "familie". Please check these.

All in all you should check your configuration on the pages "TCP/IP", "Identities" and "Filters" for valid folders. I am quite sure you will see some "empty" folders in certain places. I am very sure everything will be working again afterwards. I'd say you are facing the negative side effects of YAM's nightly builds. Things may misbehave from time to time. This is the price you have to pay for using the most recent development versions.

I did lots of upgrade procedures from older configurations to the current state and I am very sure that everything is upgraded correctly now. Thus, if everything is working again after checking your configuration, please let us know. We will close this ticket then.

**Comment by tboeckel** [comment]
**Originally on 2013-11-18 20:24:57 +0100**

___
Deleted the two logs on Joseph's request. Please note that I kept them on my machine for possible later reference.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-19 10:36:49 +0100**

___


edited my backup .config file  .configOK only for the password of one of my mailservers.& 
-named it .configTest
- made an other copy edited for other problems (JDuch Jée filters, named  it .configOK.
it contains
FI18.Name           = Jée
FI18.Remote         = N
FI18.ApplyToNew     = Y
FI18.ApplyToSent    = Y
FI18.ApplyOnReq     = Y
FI18.Combine        = 1
FI18.Field0         = 0
FI18.SubField0      = 1
FI18.CustomField0   = 
FI18.Comparison0    = 0
FI18.Match0         = Alumni
FI18.CaseSens0      = N
FI18.Substring0     = Y
FI18.DOSPattern0    = Y
FI18.SkipEncrypted0 = N
FI18.Actions        = 32
FI18.RedirectTo     = 
FI18.ForwardTo      = 
FI18.ReplyFile      = 
FI18.ExecuteCmd     = 
FI18.PlaySound      = 
FI18.MoveTo         = Jée

Installed last NB 19/11
copied .configOK to .config
Verified the Jée folder exists: OK
The other Jée -bizarresigns exist too: i did never create it that way : 
	it was always named Jée eg in my SAM440ep installs
	The name must have been changed by some application, maybe when copying
	
Launched yam
Get mesages, no new messages

Filter button could not be used on "incoming"

Opened Settings window
 JDuch filter was set correctly
Tried to view  Jée filter 
Opened the action tab
the  Move textin gadget pointed to quite another "tree item" (it is the last you  looked at, and don't know how YAM is picking up the tree-item if it is the first you look at, looking at does not generate a crash) but: 
Opened the "look for correct tree-item " right of the textin gadget 
crash - see attached crashlog

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-19 10:38:11 +0100**

___
**Attachment added:** [`Crashlog_YAMdebug_2013-11-19_09-30-48.txt`](https://yam.ch/attachments/451/Crashlog_YAMdebug_2013-11-19_09-30-48.txt) (32.1 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-19 19:46:32 +0100**

___
In (f043fb8):
 * mui/FolderRequestPopup.c: added a NULL pointer check for unresolved folders. This refs #451.

**Comment by tboeckel** [comment]
**Originally on 2013-11-19 19:50:26 +0100**

___
Replying to JosDuchIt:

> Launched yam
> Get mesages, no new messages
> 
> Filter button could not be used on "incoming"

Why not? You are omitting the basic details here.

> Tried to view  Jée filter 
> Opened the action tab
> the  Move textin gadget pointed to quite another "tree item" (it is the last you  looked at, and don't know how YAM is picking up the tree-item if it is the first you look at, looking at does not generate a crash) but: 
> Opened the "look for correct tree-item " right of the textin gadget 
> crash - see attached crashlog

That crash should be fixed with the next nightly build.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-20 11:12:52 +0100**

___
    Why not? You are omitting the basic details here.

I did note the button was ghosted, when i wanted to use it , so it did not work. I conjectured  that this might be a correct reaction if YAM remembers it filtered just before or if it noted no new messages were received in the incoming folder. Then again i doubted this was the case. 
I really cannot give more details. It was unexpected, no crash or freeze debug or snoopy  output available.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-20 13:15:16 +0100**

___
**Attachment added:** [`Crashlog_YAMdebug_2013-11-20_11-05-55.txt`](https://yam.ch/attachments/451/Crashlog_YAMdebug_2013-11-20_11-05-55.txt) (34.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-20 13:16:45 +0100**

___
   That crash should be fixed with the next nightly build.

Interface remark: Did comment on this after a crash did see, that i was not looged in
Did log in, and lost the comment :(

Here it is again:


used the settings  window
went to filters
chose the Jée filter
chose the action tab
the move textin gadget was empty
using the treebrowser i could not see the Jée folder


Went to the folder/new menu 
Entered Jée as foldername
Got a message "folder exists, do you want to continue ? If yes, folder will be erased/changed
chose continue
Got crash
crashlog joined

**Comment by tboeckel** [comment]
**Originally on 2013-11-24 19:53:37 +0100**

___
I think I found the reason for the crash. YAM used a wrong object as destination object for a notification which then caused an access to a no longer existing object as soon as the notification was triggered. Please try again with the next nightly build and reopen this ticket if it is still not fixed.

**Comment by tboeckel** [comment]
**Originally on 2013-11-24 19:53:54 +0100**

___
In (33c1627):
 * mui/FolderRequestListtree.c: set the notification for a changed folder tree for the correct object. The former approach used the NListview object instead of the NListtree object. This might have caused a crash, because the notification was never removed and a changed folder tree would then access a no longer existing object when the notification was eventually triggered. This closes #451.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-27 14:16:59 +0100**

___
Downladed the archive & installe it.
As soon as yo try to use the mouse wth the slider gadget to view other folders you get eiter very slow reatons or a freeze.

Dumpdebugbuffer  will be joined

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-27 14:21:32 +0100**

___
**Attachment added:** [`Debugdump-17-11`](https://yam.ch/attachments/451/Debugdump-17-11) (312.3 KiB)
after freeze when using folders dragbar

**Comment by jens-maus** [comment]
**Originally on 2013-11-27 19:46:17 +0100**

___
I am sorry, but the debug/crash log you provided is

  1. way too long with having catched way too much information not related to YAM and
  2. doesn't show any crash related to YAM.

So I see nothing new or related to YAM here which would tell us that the problem isn't fixed.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:45:06 +0100**

___
**Release Note:**
fixed a potential problem where YAM was overwriting filter settings.
