### ISSUE TITLE
Crash while typing in write window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#461]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-24 14:39:51 +0100**

___
## Summary

I was typing a reply in the write window when I looked up and a crash had occurred. The Grim Reaper had opened and I had pressed return after it did. I saved the crash log. I had to reboot.  The UpdateTreeStatistics() function was involved.

## Steps to reproduce
 1. Select to reply to an email.
 2. Type in a sucha way as to reproduce bug.
 3. I think I randomly found it. :-)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-24 14:40:22 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-11-25_00-27-14.txt`](https://yam.ch/attachments/461/Crashlog_YAM_2013-11-25_00-27-14.txt) (31.2 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-24 20:06:01 +0100**

___
The crash happened while YAM was automatically saving the current mail as draft. Since the draft mail handling has been completely reworked in YAM 2.9-dev it is very likely that this kind of crash has been fixed already.

Perhaps you might want to try yourself and use YAM 2.9-dev. Please remember to make a backup of all your settings files and mails, because YAM 2.9-dev will make several irreversible changes to certain files and folders. You have been warned...

If this issue should be still occur with YAM 2.9-dev then please reopen this ticket. I will close it as "fixed" for the time being.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-26 16:14:23 +0100**

___
Thanks for the quick response and fix. :-)

By the sounds of it 2.9 contains some drastic chnages like 2.7 did. If only I didn't have 1000's of emails this wouldn't bother me so much.  Even on SFS backing up little lots of large data is a nightmare.

I do wonder if an interim update for the current 2.8 would be good that includes major bug fixes that crash. IOW a final stable release before the version bump.

**Comment by tboeckel** [comment]
**Originally on 2013-11-26 16:27:10 +0100**

___
I affraid an interim release is not going to happen.

The changed draft handling is not just a single changeset which could be merged into the YAM 2.8p1 source code. It is merely a longer process which involved lots of changes until the current state. I cannot tell which change exactly might fix this crash. We are simply lacking time and man power for such an interim step. The scheduled release date is around Christmas this year (2013 that is ;)). We will only be fixing bugs until then.

You can install YAM 2.9-dev into a separate directory with a separate mail directory. Just copy over either a selection or all of your mails to this 2.9-dev mail directory for testing purposes. Your 2.8p1 mails will then be unaffected by any bugs in 2.9-dev and going back to 2.8p1 is as simple as it can be.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:02:49 +0100**

___
**Release Note:**
fixed a crash bug when in the write window the autosave functionality activates while typing.
