### ISSUE TITLE
YAM doesn't close the write window in a message without a "to" entry

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#469]
**Originally by _opionline@yahoo.de_ on 2013-12-05 00:48:22 +0100**

___
YAM doesn't close the write window in a message without a "to" entry.
Steps to reproduce:
1. Write a new message
2. add NO adress into the "To" textfield
3. click "send later"
4. click in the requester "add later"
5. the message is saved but the window is still open.
In older versions of YAM the window is closed in such case, which makes sense for me.

Used version: YAM 2.9-dev (30.11.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7366]

**Comment by tboeckel** [comment]
**Originally on 2013-12-06 20:29:46 +0100**

___
I'd say this is due to the changed handling of draft mails since YAM 2.8p1. Mails without a receiver are saved as draft mail now if the user chooses "Add later". But you are right. As the "Send later" button usually closes the window it should do so in this situation as well. However, the mail is incomplete and cannot be sent as it is. Thus I suggest to rename the "Add later" button to "Save as draft" and to let YAM close the window nevertheless.

**Comment by tboeckel** [comment]
**Originally on 2013-12-06 20:40:34 +0100**

___
In (0dcb1cd):
 * mui/WriteWindow.c: renamed the first answer of the confirmation requester if the user chooses to send a mail without a receiver from "Add later" to "Save to draft and close window" as this is what is really done. The write window will be closed, because this is the intended action of the "Send now/later" buttons. This closes #469.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:10:05 +0100**

___
**Release Note:**
restored the previous behavior of allowing a write window to be closed with no recipient being entered.
