### ISSUE TITLE
Edit a mail creates a new mail and add a space into the body

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#472]
**Originally by _opionline@yahoo.de_ on 2013-12-13 03:00:24 +0100**

___
Edit a mail creates a new mail and add a space into the body.
Steps to reproduce:
1. Create a new mail
2. click "send later"
3. go to the "Outgoing Folder"
4. select the just created mail
5. click "edit"
6. click "send later"

now you have 2 mails in the outgoing folder. The second one has a additional space into the body. You can repeat steps 4-6 and you will get a lot of mails.
Because you select a mail to edit YAM should IMHO not create another mail and something to this mail.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-13 03:02:19 +0100**

___
Sorry the last statement should be:
Because you select a mail to edit YAM should IMHO not create another mail and add something to this mail.

**Comment by tboeckel** [comment]
**Originally on 2013-12-13 06:34:56 +0100**

___
As explained in #470 already the additional mail is intentional.

Where **exactly** does the space become inserted? Just "reading" the two mails in a read window shows no visual difference except the different dates.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-13 14:29:31 +0100**

___
In #470 thboeckel wrote:
> Sorry, no. The button in the toolbar cannot carry the whole message. The mail list context menu names the corresponding entry "Edit as new" instead of just "Edit". That means that a **new** mail with the same contents will be created for editing and the old mail will be left untouched as it is. On the one hand this is done because mails in the Outgoing folder are considered "finished", as explained earlier already, and are to be sent as they are. On the other hand this additional new mail serves as a kind of "undo" function. Even if you make larger permanent changes to the new mail you still have the unchanged "original". Of course the older mail will remain in the Outgoing folder, because only the edited copy will be sent out and moved to the Sent folder.
> 
> Basically it is your task to decide which of the two mails is the one to be Sent. The other one is kept and again it is your task to delete it manually. This way nobody can complain that YAM automatically deletes stuff without user interaction.
>

It's not intuitive and not Amiga like. If the button cannot carry the whole message the button should be ghostet except in the drafts folder where the message is correct. A button should IMHO do what the message says.
The user has still the possibility to use the menu entry "edit as new".

about the additional Space:
the space is added after the first word or at the end. steps to check it:
1. Write a new message
2. type e.g. "test" into the body (no signature only "test")
3. click save as draft. (the window is still open, so close it)
4. go to drafts and select the message
5. click edit
6. in the body is now "test "
(all without quotes of course)

**Comment by tboeckel** [comment]
**Originally on 2013-12-14 03:03:31 +0100**

___
The edit button has always used the current mail and put its contents into a new mail, no matter which folder. This worked even for received mails you didn't compose yourself. This is what I would call unintuitive. This has nothing to "Amiga like" or not. All in all the main window's toolbar has more buttons than it needs to have. For example the "Read" button is quite superflous. In case the embedded read pane is active it serves no real purpose anymore in any way, because the mail is already shown automatically. And even with the read pane being disabled it is much faster to double click a mail instead of clicking it just once and then using the Read button to display it in a read window. But this is something that belongs into a separate ticket.

**Comment by tboeckel** [comment]
**Originally on 2013-12-14 03:05:20 +0100**

___
In (6530e31):
 * YAM_RE.c: the attempt to replace NUL bytes within a stream would always replace the terminating NUL byte by a space if a message consisted of a single line only without an LF at the end. By pure luck the allocated buffer was always big enough to carry an additional NUL byte to finally terminating the string again without causing a buffer overrung. Now the replacement correctly stops one byte earlier. This closes #472.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:11:56 +0100**

___
**Release Note:**
fixed a problem where editing a mail a second time added an additional superfluous white space to the mail body.

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-13 14:49:17 +0100**

___
I use the 68k version of YAM 2.10-dev (09.02.2014) and can reproduce what opiopi has reported:
Each time you edit a mail in outgoing folder and click on "send later" a new mail will created. The added "space" in subject I don`t get.

**Comment by tboeckel** [comment]
**Originally on 2014-02-13 15:08:24 +0100**

___
Replying to stellan:
> I use the 68k version of YAM 2.10-dev (09.02.2014) and can reproduce what opiopi has reported:
> Each time you edit a mail in outgoing folder and click on "send later" a new mail will created. The added "space" in subject I don`t get.

That happens intentionally. Mails in the Outgoing folder are considered "finished" and don't need further editing. However, if you wish edit them nevertheless and choose the menu item "Edit as new" you get exactly what the menu items tells you: you get a new mail. The same happens when you are trying to edit a received mail.

Only mails in the Drafts folder are considered "unfinished" and will be replaced whenever they are saved again temporarily. Hitting the "Send now" or "Send later" button for such a mail will move it to the Outgoing folder, because now it is finished an doesn't need further editing.

This difference between the Outgoing and the Drafts folder is also made more clear by the fact that doubleclicking a mail in Outgoing will open a read window like for any other received mail, while doubleclicking a mail in Drafts will open a write window to continue your editing work. Furthermore mails in Outgoing will be marked as "read" as soon as the mail was displayed as such in the usual manner (separate read window or embedded read pane). This does not happen for mails in Drafts.

So when you are editing mails in the Outgoing folder again it is your task to decide which of the two copies is the correct one that is to be sent off. The other one must be deleted manually.

I am aware that this is a big change compared to previous versions of YAM, but then the mails in Outgoing could only be distinguished by a status icon and it was not very obvious why hitting the "Send" buttons sends off some mails but leaves others. All in all the current approach is much more consistent, clear and also matches the behaviour of mail clients on other systems.

**Comment by jens-maus** [comment]
**Originally on 2014-02-13 15:21:27 +0100**

___
I agree with thore here. The only thing that coild be argued is that the toolbar text for the edit toolbar button is always "Edit" and not "Edit as new" in such cases. So if this would solve your problem please create a new ticket for that. In addition we would perhaps do good by adding an FAQ entry for that question as you will not be the only one being irritated by that change in behaviour.

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-24 01:47:22 +0100**

___
Thanks for explanation. If you habituates to the old behaviour then it is really irritate with the new one as you said. I have to change to use draft instead.
