### ISSUE TITLE
wrong character conversation after deleting attachments

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#517]
**Originally by _anonymous_ on 2014-01-29 23:17:21 +0100**

___
## Summary

After deleting one (or more) attachment from the mail, character conversation goes wrong. 

## Steps to reproduce
 1. use ISO-8859-2 charset (hungarian)
 2. the message body is babábőbőbúbü (nothing sensible) and it contains one picture as an attachment  
3. the raw message is bab=E1b=F5b=F5b=FAb=FC
4. delete the attachment
5. the message body will babĂĄbĹbĹbĂşbĂź
6. the raw message is: bab=C3=A1b=C5=91b=C5=91b=C3=BAb=C3=BC

I tried this with many mails and the bug is reproducible.

**Comment by tboeckel** [comment]
**Originally on 2014-01-30 07:48:11 +0100**

___
I can reproduce this issue. The malformed raw mail text after deleting an attachment happens because the original mail is parsed using the usual functions. These will always transform the mail text to UTF8 as the current internal representation. However, the following deletion of attachments does a very simple job an writes out all kept parts "as they are", but with the previous content-type in the header lines. Thus you end up with an UTF8 body while the headers state something like ISO-8859-2.

All in all the removal of attachment needs a complete rework, but I doubt this will happen for YAM 2.9p1. Hence I scheduled it for YAM 2.10.

**Comment by tboeckel** [comment]
**Originally on 2014-01-30 20:43:01 +0100**

___
I think I found a fast solution for this issue. Since the raw mail is recreated while deleting attachments anyway we can also change the charset of the mail part to its current in-memory representation, which is UTF8.

**Comment by jens-maus** [comment]
**Originally on 2014-01-30 20:46:02 +0100**

___
Replying to tboeckel:
> I think I found a fast solution for this issue. Since the raw mail is recreated while deleting attachments anyway we can also change the charset of the mail part to its current in-memory representation, which is UTF8.

I also thought about that Thore. But I think it is just a quick hack to get things going. IMHO it would be better to simply reencode the UTF-8 to the old target codeset (ISO-8859-2) after having cropped the attachments instead of saving the mails with UTF-8 encoding. This should also be quite straight forward IMHO.

**Comment by tboeckel** [comment]
**Originally on 2014-01-30 20:46:23 +0100**

___
In (705e01a):
 * YAM_MA.c: force the charset of plain texts to UTF8 when removing attachments from mails. This is not a 100% clean solution but it at leasts keeps non 7bit ASCII characters in a suitable encoding which does not malform them. This closes #517.
