### ISSUE TITLE
Cutted text on the about window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#524]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-05 15:00:19 +0100**

___
On the about window certain long text will be cutted at some point...
Tested with latest nightly of YAM (r7672) and latest MUI 4.0 (svn r3184)

See grab

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-05 15:00:46 +0100**

___
**Attachment added:** `cutted_text.png` (71.2 KiB)
![cutted_text.png](https://yam.ch/attachments/524/cutted_text.png)

**Comment by jens-maus** [comment]
**Originally on 2014-02-05 15:34:02 +0100**

___
Well, it is up to the translator to ensure that the text in question (in Crawling.mcc) will not be truncated. As you are the main translator of the italian translation I would suggest that you revise your text to be not truncated.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-06 21:47:03 +0100**

___
Yeah you right, to be sure i also test it with the old MUI4 and it appear the same, just i didn't noticed the issue using other themes ..
I might changes it eventually (even if i already try to reduce such text as small as possible) but ehm i would prefer if you can increase directly the availible space, even a couple of pixels might be enough :-)

**Comment by tboeckel** [comment]
**Originally on 2014-02-06 22:20:15 +0100**

___
Unfortunately it is impossible to let the crawling object dominate the window's size, because it is a subclass of Virtgroup.mui. On the one hand such objects can have infinite size in both directions which is the reason why the object can display a very high text object by scrolling vertically. On the other hand the same applies for the horizontal direction. If an object inside a virtual group is too wide to fit into the window it will be clipped.  That is why virtual groups usually get scrollbars, but for the crawling object scrollbars are absolutely not desired.

Thus limiting the text width is the only way to make sure that the text is completely visible. An additional stumbling block is the fact the user might set a wrong font size, i.e. by making the "small" font bigger than the normal font. This will definitely lead to clipped text portions. Thus all you can do is to put in enough line feeds to make the text fit for your needs and adapt it further in case someone complains.
