### ISSUE TITLE
No-indexing startup option

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#54]
**Originally by _ojciec_swiety@wp.pl_ on 2010-03-04 18:51:38 +0100**

___
Would be possible to add a startup option to skip folder re-indexing? I've just searched for an older email in one of my backup CDs. So I run YAM with maildir option pointing to that CD. Unfortunately, YAM insisted on updating the indexes which is rather hopeless on read-only media. It tried to write to disc on each single mail so canceling zillions of requesters was not an option. Finally I decided to copy whole YAM dir to t: and redirect YAM there. It worked but reindexing took really long (tons of emails). That's why my suggestion to add an option for skipping indexing procedure - it would enable fast access to folders created by older versions of YAM.

**Comment by jens-maus** [comment]
**Originally on 2010-03-09 12:36:25 +0100**

___
This sounds reasonable and actually doable. We could also probably add a possibility that YAM may interactively ask the user if he wants the indexing done right away or later. However, the question remains what happens if the inbox or any other mandatory folder needs indexing, what should happen then?

**Comment by tboeckel** [comment]
**Originally on 2010-12-19 07:21:59 +0100**

___
I think the most important point is to check here is why YAM is trying to recreate the index at all. Is it just because the dates of the folder and the .findex file were altered and thus YAM thinks the index is outdated/corrupted or is there a another reason? Or is it because the backed up index on the CD has an older version than YAM currently uses?

Second, how should YAM react in case a mail's state has to be changed (i.e. from "new/unread" to "read"? This requires write access to the disk or you will get tons of further "disk is write protected" requesters and the next time you start YAM the mails will have their old state. Although this must be acceptable.

One solution would be to either accept index files from read-only media as they are and never perform a rescan, but this would mean old mail backups cannot be used with future versions of YAM and a changed index file layout. 

Doing the rescan once is no 100% solution either, as YAM will automatically flush unused indices from memory and reload them when necessary, but this would result in yet another rescan. In this case the index must be marked as "not flushable" to avoid the constant rescan. But this all only holds true as long as YAM is not restarted. After a restart the scan will be due again.

From my point of view it all comes down to one question: why is the index rebuilding necessary at all and can any logic inside YAM make this necessity more tolerable? The way YAM handles its mails simply requires a disk that can be written to.

Opinions?

**Comment by tboeckel** [comment]
**Originally on 2011-03-15 15:59:02 +0100**

___
Closing this ticket as I really don't know how to fix it. If the index file is deleted because it is outdated keeping a backup of it makes no sense, since the backed up file is still outdated and cannot be used.
