### ISSUE TITLE
YAM failed returncode 10

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#552]
**Originally by _antibike@web.de_ on 2014-04-23 11:53:39 +0200**

___
## Summary
Die letzten Nightly Builds lassen sich nicht mehr starten. Es gibt nur den Rückgabewert 10.

## Steps to reproduce
 1. run YAM

## Expected results
YAM startet

## Actual results
YAM failed returncode 10

## Notes

**Comment by tboeckel** [comment]
**Originally on 2014-04-23 14:31:22 +0200**

___
Since YAM 2.9p1 is using UTF8 catalogs codesets.library is required when dealing with translated strings. Unfortunately there is a hen-and-egg problem when the found codesets.library does not meet YAM's minimum version requirements. In this case YAM will open a requester with no text at all, because it is unable to obtain translated strings.

If will change this to use at least the built-in english strings if codesets.library is not available or too old.

**Comment by tboeckel** [comment]
**Originally on 2014-04-23 14:36:15 +0200**

___
In (c6cfba8):
* YAM.c, Locale.c: fixed an empty error message in case codesets.library does not meet YAM's requirements but would be required for the translated error message. YAM will fall back to the built-in strings then. This closes #552.
