### ISSUE TITLE
HTML preview accents not correctly shown

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#557]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-05-08 09:57:45 +0200**

___
## Summary

When displaying html attachment directly from within yam which opens OWB and shows the content, caracters with accents aren't shown correctly but are replaced by "?". The charset is ISO-8859-1 in yam. Now strange is, that when saving the same html attachment to ram and then displaying it in OWB, it is displayed correctly!

## Steps to reproduce
 1. display the html attachment of the mail
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-05-08 09:58:55 +0200**

___
**Attachment added:** [`Fwd__RE__lieu_de_rencontre_du_4_juin_2014.eml`](https://yam.ch/attachments/557/Fwd__RE__lieu_de_rencontre_du_4_juin_2014.eml) (33.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 16:12:23 +0200**

___
The reason is quite simple:

00:W:       YAM_RE.c:1639:the specified codeset 'windows-1258' wasn't found in codesets.library

I really can't tell right now if codesets.library is just missing a (not so) well known codeset or if Windows-1258 is no valid codeset at all. But at least that is why you get the wrong characters.

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 16:13:43 +0200**

___
Oh, I just took a look at Thunderbird's codeset menu and Windows-1258 seems to be the Windows codeset for Vietnam. Not very common in western Europe...

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 16:20:05 +0200**

___
A possible solution without any code change is to supply a suitable conversion table in LIBS:charsets/windows-1258.txt. codesets.library will use that file for the conversion automatically if it exists.

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 16:24:48 +0200**

___
**Attachment added:** [`windows-1258.txt`](https://yam.ch/attachments/557/windows-1258.txt) (9.1 KiB)
Windows-1258 conversion table

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 16:25:47 +0200**

___
Just use the attached conversion table. For me the mail is displayed correctly then.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-05-09 07:12:24 +0200**

___
Yes, thanks, this confersion table does correct the problem! Perhaps it would be a good idea to add it also for next codeset archive.

But I do have another one here, also e-mail received from somebody in which there are accented caracters replaced by ?. But this time, the problem seems only shown in YAM, when opening the html part in OWB it gets displayed correctly. I attach the mail.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-05-09 07:13:26 +0200**

___
**Attachment added:** [`Fwd__Catechese.eml`](https://yam.ch/attachments/557/Fwd__Catechese.eml) (6.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-05-09 14:11:03 +0200**

___
Replying to rmsyam:
> Yes, thanks, this confersion table does correct the problem! Perhaps it would be a good idea to add it also for next codeset archive.

I committed that table already along with some other Windows-125x tables.

> But I do have another one here, also e-mail received from somebody in which there are accented caracters replaced by ?. But this time, the problem seems only shown in YAM, when opening the html part in OWB it gets displayed correctly. I attach the mail.

This mail show exactly the same problem as the example mail of #432. There are two alternative text and HTML part which both claim to be UTF8 encoded. While this is true for the HTML part the plain text part seems to be Windows-1251 encoded, but definitely not UTF8. YAM will then try to convert this wrong UTF8 encoded text back to ISO-8859-1 which of course must fail. Hence you get the ? characters.

There is nothing we can do about this, because it is a fault of the sending mail client.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-05-09 15:05:44 +0200**

___
Ok, understood! Thanks for having checked.
