### ISSUE TITLE
Send later and sending keeps the original email in the Outgoing folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#579]
**Originally by _pferrucci@sfr.fr_ on 2014-08-23 19:36:47 +0200**

___
## Summary

If you create a new email and click "Send later". When you open it and "send" it YAM keeps the original email in the Outgoing folder

## Steps to reproduce
 1. create a new email
 2. click "send later", the email goes into the outgoing folder
 3. go to that folder
 4. double-click the email to open it
 5. click send

## Expected results

Mail is sent. Email item is removed of the outgoing folder.

## Actual results

A copy of the email is created in the outgoing folder. Then one of these emails is sent (it can then be found in the Sent folder).
The second email is left in the Outgoing folder.

## Notes

**Comment by tboeckel** [comment]
**Originally on 2014-08-24 19:11:40 +0200**

___
Double clicking a mail in the Outgoing folder will open it (like any other mail) for reading only. There is no "Send now" button in the read window. And clicking on "Send" in the main window's tool bar correctly sends off any mail in Outgoing and closes their read windows.

Are you sure you are referring to the nightly build of YAM 2.10-dev? You forgot to specify the exact version anyway. There is no single nightly build, hence the exact date or SVN revision is absolutely required.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-08-24 19:56:23 +0200**

___
It's r8198 (I thought it was about GCC as it is written next to the GCC version and not next to the compilation date. You should change this IMO.

Ok, I'm wrong with the steps to reproduce. Replace point 4 with:
4. click the email to select it and click on the "Edit" button

**Comment by tboeckel** [comment]
**Originally on 2014-08-25 20:58:22 +0200**

___
That behaviour is intentional since YAM 2.9p1. Mails in Outgoing are considered "finished", because you clicked on "Send later". If you choose to edit them again the first version of the mail is kept and you start editing a new mail. This is exactly the same as editing a mail in any other folder except the Drafts folder.

I know, this is a big change compared to previous versions, but now the handling of all mails is always consistent. Only mails in the Drafts folder are considered "unfinished". Before you had a mixture of "finished" and "unfinished" mails in one folder and only a single icon in the mail list told you the difference. Even clicking on "Send" did not sent off all mails in Outgoing but kept the "unfinished/on hold" mails. Now the Outgoing folder contains all mails that are really "finished" and are ready to be sent off.

If you think that YAM's SVN revision should be placed somewhere else then please open a new ticket for this, as this is not related to this issue in any way.
