### ISSUE TITLE
DSI error when try to reopen YAM from its mailbox appicon

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#588]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 23:01:06 +0200**

___
This is not happening all the time, but quite often. When I run YAM to check my messages and iconify the program, when I try to reopen YAM to check for new arrived messages via the mailbox appicon of YAM sometimes I got a DSI error, which is attached here. MUIMaster library problem?

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 23:01:20 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-10-20_23-55-47.txt`](https://yam.ch/attachments/588/Crashlog_YAM_2014-10-20_23-55-47.txt) (45.3 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-10-21 06:20:34 +0200**

___
This is definitely a MUI bug. In fact it happens when MUI is trying to determine the object's font height. In this particular case the font pointer is NULL. But I really wonder how a simple text object can end up without a font.

One possible reason would be trashed memory, although a plain NULL pointer instead of random data is quite unprobable. I will see how this can be solved. In the meantime please open a new ticket in MUI's bugtracker including the crashlog.

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-21 15:22:25 +0200**

___
Cannot register on MUIdev's site. This is what I got everytime:

Submission rejected as potential spam
StopForumSpam says this is spam (username [83.64])

**Comment by tboeckel** [comment]
**Originally on 2014-11-09 20:16:44 +0100**

___
The bug in MUI has been fixed in the meantime.
