### ISSUE TITLE
All existing files in inbox folder doubled

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#593]
**Originally by _JDuch@fulladsl.be_ on 2015-03-03 11:17:46 +0100**

___
## Summary
All files in my inbox present before installing  the latest debug version 26/2/2015 seem to be doubled.
I have downloaded & installed this version on 27/2

Today, detecting some messages that apparently were sent twice, i tried to delete some, that was ok, but when i tried to delete second ones  i got the error message "Couldn't transfer mail  to folder "Corbeille"
Apparently 'phantom files' are shonwn by YAM in the inbox view.
Checking with list command, no doubles appeared.
Doubles appeared in the .index file though

I got rid of them renaming the .index file & having Yam reconstitute it

## Steps to reproduce
Not sure about this
 1. 
 2.

## Notes

**Comment by tboeckel** [comment]
**Originally on 2015-03-12 13:21:03 +0100**

___
First of all, which platform this happened on? You gave exactly **no** information about your system.

Is this something you can reproduce or did it happen just once? Keep in mind that AmigaOS has memory protection and hence any gone nuts program can cause arbitrary harm which eventually causes YAM to save its folder index twice. At least this explains why a mail can be moved/deleted only once and the second attempt fails with the error message you got.

As you already stated a simple reindexing operation cures this issue. As long as this issue cannot be reproduced there is nothing we could do against it. If it happens again for you, then please give as many information as possible about what you were doing (and before) and if any other application did crash or misbehave before. Otherwise we are left with just a simple "it crashes".

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2015-03-27 03:31:30 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
