### ISSUE TITLE
The help menu generates URL's in which a string "<EMPTY>en:" is introduced under OS4.1FE and YAM2.10dev 26/02/2015

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#598]
**Originally by _JDuch@fulladsl.be_ on 2015-03-25 10:50:37 +0100**

___
## Summary
When trying to open the help pages with the help menus a string "<EMPTY>en:" is introduced in the URL &  passed to the "double click" script or command (eg urlopen)
It has been verified that this does not happen for 2.8p1 neither under OS4.1Upd6 nor under OS4.1FE

It happens with 2.10 nightly build under OS4.1FE, not under OS4.1 Uod6

## Steps to reproduce
 1.Use the help menu 
 2.chose Contente or arexx interface

## Expected results
the proper page should be opened

## Actual results
the browser opens on the site but not on the exact page , the URL with inserted string is not recognised 
## Notes

**Comment by tboeckel** [comment]
**Originally on 2015-03-25 13:51:53 +0100**

___
It is obvious that YAM 2.8p1 is not affected, because the "<EMPTY>" tag was introduced when we switched the translation process to transifex and .po files. However, it is very hard to believe that only OS4.1FE is affected while OS4.1 update #6 is not.

However, is it possible that you are using "british-english" as your preferred language? This is the only translation which has the "<EMPTY>" tag in a place where it should not be.

**Comment by tboeckel** [comment]
**Originally on 2015-03-25 16:14:58 +0100**

___
I just fixed the british english translation. Please try again with the next nightly build.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-03-30 21:21:09 +0200**

___
locale is indeed english-british_ISO-8859-15
I checked with NB 26/03
instead of inserting <EMPTY>en:

it now inserts
<EMPTY>:

I'l check again under OS4.1Upd6

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-03-30 21:34:29 +0200**

___
I checked again under OS4.1 Updt 6
The problem was not directly visible there because locale was set to 
"english"
Changing to english-british_ISO-8859-15 the results were identical as under OS4.1 FE

**Comment by tboeckel** [comment]
**Originally on 2015-03-30 22:26:02 +0200**

___
I suppose the "OS4.1FE" system is a complete different machine than the "OS4.1 update 6" one. Correct?

Is it possible that you have a british english catalog file in two locations on your FE system and YAM uses an older version which still contains the "<EMPTY>" tag? There is not a single occurance of "<EMPTY>" in the internal english strings.

So please check your **complete** harddisk of all your systems for possible duplicate YAM catalog files. There should be no other catalog files except those in <YAM's directory>/Catalogs.

**Comment by tboeckel** [comment]
**Originally on 2015-03-30 22:32:26 +0200**

___
Just for completeness, the most recent version of the british english catalog is 10.8312 (25.03.2015). If you get something else reported you have definitely not the most recent version installed or YAM is not using it, because a duplicate catalog file with the same name in a path which is searched earlier is blocking it.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-03-31 08:56:12 +0200**

___
My Yam 2.10 install is the same (intalled on dh1: partition) wether i launch it with OS4.1FE (dh3:) or OS4.1Upd6(dh0:) so when i update YAM2.10 dev the catalog files are the same.
Can a .config file point to a previous install?

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-03-31 08:59:30 +0200**

___
9.Stock:Internet/YAM_2.10/catalogs/english-british> list
YAM.catalog                    3192 ----rw-d Thursday  01:00:13

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-03-31 09:20:55 +0200**

___
I have been looking into the snoopy output 
- when launching YAM 2.10
- when trying to open the help.documentation page

I don't see any call trying to open a catalog except for OWB (help menu usage)
2641 : ODYSSEY         : FAIL # Open("LOCALE:Catalogs/english-british_US_ASCII/OWB.catalog",OLD)[0x00000000] [77uS]

In the launch trace  none appears and as for locale i do see a huge number of
2698 : YAM.debug       : FAIL # Open("/usr/lib/locale/LC_TIME/C",OLD)[0x00000000] [42uS]

all failing.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-03-31 09:43:37 +0200**

___
As a test i renamed the 
DH1:Internet/YAM_2.10/catalogs/english-british 
to
DH1:Internet/YAM_2.10/catalogs/english--british
and got what seems to be exactly the same behavior 
eg when opening the help menu


00085 : urlopen         : -----> RunCommand(0x176951ED "urlopen",,""http://yam.ch/wiki/<EMPTY>:Documentation/ARexxAPI"",52)

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2015-03-31 19:25:09 +0200**

___
The error seems to be in the Changeset 8312, see the last Change (line 9724)
The entry schould be empty IMHO for english and not contain the Word EMPTY.

**Comment by tboeckel** [comment]
**Originally on 2015-03-31 19:38:31 +0200**

___
Replying to anonymous:
> The error seems to be in the Changeset 8312, see the last Change (line 9724)
> The entry schould be empty IMHO for english and not contain the Word EMPTY.

Wrong. The line does not contain the word "EMPTY", but the special sequence "<EMPTY>" which will let FlexCat generate an empty string, which is exactly the desired string. Honestly, please read the instructions, either directly in the .po file above the string to be translated or in the "Details" section of transifex.

**Comment by tboeckel** [comment]
**Originally on 2015-03-31 19:39:02 +0200**

___
Replying to JosDuchIt:
> My Yam 2.10 install is the same (intalled on dh1: partition) wether i launch it with OS4.1FE (dh3:) or OS4.1Upd6(dh0:) so when i update YAM2.10 dev the catalog files are the same.
> Can a .config file point to a previous install?

No. The catalog is loaded **long** before any configuration file.

**Comment by tboeckel** [comment]
**Originally on 2015-03-31 19:45:02 +0200**

___
@JosDuchIt:

I asked you check for duplicate files named "YAM.catalog" in any path that LOCALE: points to. As long as you don't do that and confirm that there are **no** duplicate files any further discussion here is senseless. Posting the size of the catalog file does not help either. And you know that Snoopy does not log **all** calls to dos.library by default. Hence the call you might be looking for and which does not get logged probably needs to be activated first.

You can also check a hexdump of the YAM binary and the british english catalog yourself and you will see that there is not a single occurence of the string "<EMPTY>" anywhere. However, if you still get it inserted nevertheless it definitely stems from anywhere else than the current YAM binary or catalog files.

To make it short: do this check for duplicate files. Otherwise we are running in circles here and don't get any step forward.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-04-01 13:52:08 +0200**

___

@tboeckel
OS4.1FE:> find locale: NAME YAM.catalog
7.Amiga OS 4:> 

Is this you are asking for ?

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2015-04-01 14:05:37 +0200**

___
@tboeckel 

9.Stock:Internet/YAM_2.10/catalogs/english-british> find CONTENTS EMPTY  
YAM.catalog                   3192 ----rw-d 26/03/2015 01h00  

9.Stock:Internet/YAM_2.10/catalogs/english-british> find CONTENTS "<EMPTY>"
YAM.catalog                   3192 ----rw-d 26/03/2015 01h00  

9.Stock:Internet/YAM_2.10/catalogs/english-british> find CONTENTS "<EMPTY>:"
9.Stock:Internet/YAM_2.10/catalogs/english-british>

**Comment by tboeckel** [comment]
**Originally on 2015-04-01 19:52:50 +0200**

___
Ok, I must appologize. It is a bug in FlexCat which caused that dreaded "<EMPTY>" string to make it into the english british catalog file. I just commited a fix for that. I will provide a replacement catalog until the fixed version is used on our build server.

Sorry for all the fuss.

**Comment by tboeckel** [comment]
**Originally on 2015-04-01 19:53:44 +0200**

___
**Attachment added:** [`english-british.catalog`](https://yam.ch/attachments/598/english-british.catalog) (3.1 KiB)
fixed english-british catalog file without "<EMPTY>" string

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2015-04-04 09:04:46 +0200**

___
I verified the locale: for a YAM.catalog  in both OS4.1FE and OS4.1Updt6 partitions
On my side i can anly add i do have other YAM installations 2.8p1 2.9 etc 
and that i am using the latest .debug version
