### ISSUE TITLE
Snapshot column widths in Preselect window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#60]
**Originally by _video@got.net_ on 2010-03-04 19:08:47 +0100**

___
Can the column positions in the preselect window be made snapshotable?

The column positions on the preselect window will not snapshot like the other windows will, and the download goes easily three times faster if the column positions are locked (sibce column positions no longer need to be computed, I assume). Hence, every time I use the preselect I grab the columns and move them slightly to lock them in place. This often crashes the machine, [I suppose that aspect should be a bug report] but the download speedup is worth it anyway. :^)

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 17:23:47 +0100**

___
I agree that the column width of the preselection windows should be snapshotable. So I flag this ticket to be addressed in the next YAM version, however with low priority.

**Comment by tboeckel** [comment]
**Originally on 2010-05-28 09:54:10 +0200**

___
The solution is not as easy as one might think on the first glance. This is because MUI will invoke MUIM_Export for existing objects only.

This means that the preselection list can be snapshotted, but currently only by snapshotting the main window, NOT the preselection window. While this may sound unfortunate, the biggest drawback is yet to come...

As soon as the preselection window is closed again after a transfer the next snapshot action will remove the previously remembered information about the preselection list again from the ENV:MUI/YAM.cfg file, because the object no longer exists and thus there is no configuration to be saved now. This is how MUI handles its objects. Only living objects at the time of MUIM_Export will be respected.

Thus we either live with the non-snapshotable preselection list or we find another way how to workaround this issue. One solution would be to have the preselection/transfer window being alive all the time and just open/close the window as needed. But this will consume memory even when no preselection/transfer window is visible.

**Comment by tboeckel** [comment]
**Originally on 2010-10-27 12:59:32 +0200**

___
In (0918725):
 * mui/PreselectionWindow.c, YAM_UT.c: the column layout of the preselection
  window can be saved permanently. This is accomplished by using the new
  Base64Dataspace class to store the layout of the dynamically added NList
  object. MUI itself will save the window's dimensions, but I cannot save
  further exported data by MUIM_Export of already dead objects. This is why
  we have to take this detour. This finally closes #60.
