### ISSUE TITLE
YAM generates error message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#606]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-21 09:47:14 +0200**

___
## Summary

Since nightly build from today, I get hits in the log, when I clear warnings in TCP/IP settings. I attach a log.

## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-21 09:47:41 +0200**

___
**Attachment added:** [`yam_log.txt`](https://yam.ch/attachments/606/yam_log.txt) (0.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2015-08-21 20:21:16 +0200**

___
In (11f4aa9):
* mui/TCPIPConfigPage.c: the update of the ignored warnings after clearing them will no longer invoke the update method synchronously, but asynchronouly instead. This is necessary, because the "clear" method is invoked from within an OM_SET method and that method will be continued to be executed after the object has been disposed and hence cause a crash. This closes #606.
