### ISSUE TITLE
Using copy keystroke (Amiga+C) makes YAM2.10dev nightly build crash

### ISSUE THREAD

**Issue by javierdlr** [jens-maus/yam#635]
On embedded read window copy keysstroke (Amiga+C) to copy to clipboard some text makes YAM2.10dev (9-08-2016) nightly build crash.
[Crashlog_TextEditor.mcc clipboard server_2016-08-09_23-45-11.txt](https://github.com/jens-maus/yam/files/409930/Crashlog_TextEditor.mcc.clipboard.server_2016-08-09_23-45-11.txt)

**Comment by javierdlr** [comment]
looking at crashlog seems is TextEditor.mcc 15.47 bug, tested with TextEditor.mcc 15.46 no problems using AMIGA+C keystroke to copy to clipboard text.

**Comment by tboeckel** [comment]
Unfortunately your crashlog cannot be found by github. And if you are already sure that this is a bug of TE.mcc instead of YAM, then it would be a good idea to open a new issue directly in [https://github.com/amiga-mui/texteditor/issues](TE.mcc's bugtracker) including a proper crashlog instead of here.

I think the reason why your crashlog cannot be found is due to the spaces contained in the filename. So if you upload a new crashlog please make sure to remove or replace any spaces before.

**Comment by javierdlr** [comment]
ok. will upload/cretae new tickey on TE.mcc ASAP.

2016-08-10 7:33 GMT+02:00 Thore Böckelmann <notifications@github.com>:

**Comment by tboeckel** [comment]
Fixed in TextEditor.mcc.
