### ISSUE TITLE
Crash on YAM 2.10 Dev when getting mail from server

### ISSUE THREAD

**Issue by Hypexed** [jens-maus/yam#640]
Running Dev build 2.10 from 14/9/2016.

I don't recall updating YAM or making any changes but lately it has been very unstable. Almost every time I run it and check my mail it crashes. The crash is not recoverable. I have to reboot my system which results in YAM rebuilding the index for folders that were opened in the process. Some of these have thousands of files and it can take ages to rebuild it. Perhaps a backup index should be put in place when the orginal is corrupted.

To recreate the crash I:
Open YAM.
Press Get button.
The transfer window opens and soon after I see a crash.

As you wil l see from the crash logs the crash can be quite severe. I've collected two types of crashes. Attached here.

[Crashlog_YAM_2016-09-17_03-16-05.txt](https://github.com/jens-maus/yam/files/480613/Crashlog_YAM_2016-09-17_03-16-05.txt)
[Crashlog_YAM_2016-09-16_01-29-16.txt](https://github.com/jens-maus/yam/files/480612/Crashlog_YAM_2016-09-16_01-29-16.txt)

**Comment by tboeckel** [comment]
AmiSSL3 is known to trash memory. If your provider changed the certificates recently this of course might trigger excatly this issue, which the old certificate did not trigger.

I must admit that this conclusion is not very obvious, especially since the crashlog mentions NList on the way to the final crash. But the sequence of YAM, NListview.mcc (AddHorizontalScroller), YAM's transfer window and finally MUI's Notify class does not really make sense.

**Comment by Hypexed** [comment]
Thanks for looking into it. Can you tell me where you get AmiSSL from? I see no obvious functions there. But I'm not familiar with it either. Given SSL is be made obsolete by TLS it might be a good time to update SSL. I don't know the details with SSL on OS4 but being system standard would be good with a stable modern version.

YAM has been stable last few days but I will update the classes such as NList to see if that improves it. 

I must say I'm rather annoyed at the move to GitHub. Apart from needing to setup yet another account, I have experience on my PowerBook where GitHub complains if you are not using the latest browser version. I managed to get it working with Odyssey but not fully as I can't upload files so have to drag them over to my Mac and upload there. I like to post bug reports from the machine it crashed on as that is where I collect the crash logs. But because OS4 web browsers are always obsolete I can't do this anymore. That said I haven't tested TimberWolf.

**Comment by tboeckel** [comment]
Most probably you already have AmiSSL 3.6 installed, otherwise you would not be able to connect to any modern ISP. Even browsers like IBrowse need AmiSSL to establish https connections. But it is exactly this old and ancient AmiSSL 3.6, which causes all the trouble. Even worse, it is linked against OpenSSL 0.9.6, which is outdated since many years by now.

We are currently working on AmiSSL4 linked against OpenSSL 1.1.0, but it will still take some time until it is finished and ready to be released.

**Comment by Hypexed** [comment]
Sounds good. Thanks. In the meantime I notice I got a message about an unknown certificate from Symantec. I accepted it and it seems to work okay. For now YAM has been stable and let's hope it stays that way. I'll also update my classes.

**Comment by jens-maus** [comment]
Issue seems to be resolved.
