### ISSUE TITLE
Not fixed: No connection to Freenet SMTP outbox server

### ISSUE THREAD

**Issue by halle-saale** [jens-maus/yam#654]
## Submission type
  - Bug report
Regarding to a previous report: https://github.com/jens-maus/yam/issues/631#event-951882193

## YAM version
YAM 2.10 developer version from February 14th

## Used operating system
  - AmigaOS3/m68k 

## Used Amiga system
- Amiga 1200 with Blizzard 1230 IV

## Expected behaviour you didn't see
Sorry, but it is still not possible to send mails via the Freenet SMTP server!
After about five minutes of testing the connection, it is canceled and a message appears saying:
No connection to SMTP server

## Unexpected behaviour you saw
[...]

## Steps to reproduce the problem
I have created a debug file using YAM with the command:
YAM DEBUG >RAM:Debug.txt

If there is an option to create more output please tell me because this file only has few information.

**Comment by halle-saale** [comment]
[Debug1.TXT](https://github.com/jens-maus/yam/files/799454/Debug1.TXT)

**Comment by jens-maus** [comment]
@halle-saale It seems the issue is caused by too slow m68k hardware not being able to calculate initial encryption initialization fast enough (see https://github.com/jens-maus/amissl/issues/11). As a work around please use the following config option in `YAM:.config`:

```
DefaultSSLCiphers        = AES256-SHA
```

So please add/change that line in your configuration file and restart YAM. Then afterwards try if this improves the situation.

**Comment by halle-saale** [comment]
Frankly spoken, this was also my guess. Because all other connections - arcor as well as Telekom - works fine and without any problems.
Thank you for the hint, I will try it.

**Comment by halle-saale** [comment]
Mh, unfortunately it did not help. After four minutes the same message popped up.

**Comment by jens-maus** [comment]
@halle-saale Then please also try the following cipher type:

```
DefaultSSLCiphers        = AES128-SHA
```

If this also doesn't help, I am afraid but then it really seems your real m68k system is really too underpowered :(

**Comment by Weber-Frank** [comment]
Did you unlock your access for smtp? see here: http://kundenservice.freenet.de/artikel/1685

**Comment by halle-saale** [comment]
@Weber-Frank: Thanks for the hint. But yes, of course, because so far I used my iMac with the Mail program to check my mails. Worked fine!

@jens-maus: I also tried your second hint but as before YAM stopped after four minutes.
Two things I do not understand:
1.) Should YAM - using your different defaultSSLCiphers options - not take a longer time to try to establish the connection? Why did it also stop already after 4 minutes?
2.) With arcor, YAM can establish a connection using SSL/TLS and the port 465. For freenet, there is also such an option, but it does not work. Is it completely different?

**Comment by jens-maus** [comment]
@halle-saale Why should YAM take a longer time with my suggested `DefaultSSLCipher` setting? This problem seems to be that the freenet server will not wait 4 minutes until your Amiga system has finished its calculations and rather drop the connection because of prolonged inactivity. And perhaps the mail server of arcor seem to wait a longer time and thus doesn't drop the connection after 4-5 minutes like the freenet server.

However, to better understand that really it takes to long please try to run the following command in a shell:

```
AmiSSL:openssl s_client -connect mx.freenet.de:465
```

And also please try:

```
AmiSSL:openssl s_client -cipher AES128-SHA -connect mx.freenet.de:465
```

And please make sure to measure the time from start of these commands until they are finished and either finish with `220 mx.freenet.de ...` or they end up with a Connection drop. So please state the time and also if the command ended up with a final `220 mx.freenet.de` line or not.

And also please redo the same command but with specifying the smtp server name for arcor.

**Comment by jerseywurzel** [comment]
@halle-saale @jens-maus @Weber-Frank 
Using the latest AmiSSL, I tried this:
Option 1 (no Cipher) took 15 minutes before I cancelled the command. It didn`t appear to connect or drop. The mouse pointer became very slow and jerky, showing that it was doing something which wasn't visible.
Option2 (Cipher AES128) took 30s and connected 220 mx6.freenet.de
I hope that helps?

**Comment by halle-saale** [comment]
My results (arcor1 and freenet1 showing the results without cipher command):
For arcor both versions report the line "220 smtp.vodafonemail.xion.oxcs.net ESMTP ready" after about 20 seconds. After another minute the Shell is ready for the next commands.

For freenet1 the output also comes within about 20 seconds but without a 220 line. The last line is "Verify return code: 0 (ok). After about 3:34 minutes the it ended with "Extended master secret: 0".
Using the cipher command, the output comes also within 20 seconds finishing with "220 mx9.freenet.de ESMTP Exim 4. 85 Sun, 26 Feb 2017 18:07:29 +0100".
After another two minutes the Shell writes: "421 mx9.freenet.de: SMTP command timeout - closing connection" and "read:errno=0"

Thanks for your time and your efforts!

[arcor1.txt](https://github.com/jens-maus/yam/files/802121/arcor1.txt)
[arcor2.txt](https://github.com/jens-maus/yam/files/802120/arcor2.txt)
[freenet1.txt](https://github.com/jens-maus/yam/files/802123/freenet1.txt)
[freenet2.txt](https://github.com/jens-maus/yam/files/802122/freenet2.txt)

**Comment by halle-saale** [comment]
Problem solved!
Obviously my reports could help improving some SSL options, because after installing the update of AmiSSL 4.1, now I can connect to the freenet outbox server even using port 587.
Great! Thanks a lot!
