### ISSUE TITLE
Jump to bottom with "more" in filters

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#78]
**Originally by _mario@cattaneo.de_ on 2010-03-04 20:26:35 +0100**

___
Would be nice if YAM-prefs jumped to the bottom of the list, when you add a filter rule with "more". So you see right away what's going on.

**Comment by tboeckel** [comment]
**Originally on 2013-07-09 10:00:41 +0200**

___
In (870fe06):
 * YAM_CO.c, YAM_COg.c, mui/FilterRuleList.c, mui/SearchControlGroup.c: turned the search control group object into a subclass of ObjectListItem to be able to put it under control of the ObjectList class. This partly refs #78 and also partly refs #79.

**Comment by tboeckel** [comment]
**Originally on 2013-07-11 15:41:18 +0200**

___
In (b97703a):
 * YAM_CO.c, mui/FilterRuleList.c, mui/SearchControlGroup.c: the single filter rules can now be removed from any position instead of the last rule only. For this each rule item got the typical "+" and "-" buttons for adding and removing. This closes #78 and closes #79.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:29:47 +0100**

___
**Release Note:**
when adding new filters YAM will now automatically jump to the bottom of the filter rule list.
