### ISSUE TITLE
Allow removal of compar. not only from the bottom of filter

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#79]
**Originally by _mario@cattaneo.de_ on 2010-03-04 20:27:54 +0100**

___
Would be nice, if one can remove any of the comparisons of the filter and not just the last one. Right now, to delete one out of the middle you have top copy and replace it with the last one and then remove that one. Not smooth. ;)

**Comment by tboeckel** [comment]
**Originally on 2013-07-09 10:00:41 +0200**

___
In (870fe06):
 * YAM_CO.c, YAM_COg.c, mui/FilterRuleList.c, mui/SearchControlGroup.c: turned the search control group object into a subclass of ObjectListItem to be able to put it under control of the ObjectList class. This partly refs #78 and also partly refs #79.

**Comment by tboeckel** [comment]
**Originally on 2013-07-11 15:41:18 +0200**

___
In (b97703a):
 * YAM_CO.c, mui/FilterRuleList.c, mui/SearchControlGroup.c: the single filter rules can now be removed from any position instead of the last rule only. For this each rule item got the typical "+" and "-" buttons for adding and removing. This closes #78 and closes #79.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:19:57 +0100**

___
**Release Note:**
any rule of a configured filter can now be removed or an additional one added in between instead of allowing only to add/delete rules to/from the bottom of the rule list.
